// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// VirtualizationInterfacesBulkPartialUpdateReader is a Reader for the VirtualizationInterfacesBulkPartialUpdate structure.
type VirtualizationInterfacesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationInterfacesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationInterfacesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /virtualization/interfaces/] virtualization_interfaces_bulk_partial_update", response, response.Code())
	}
}

// NewVirtualizationInterfacesBulkPartialUpdateOK creates a VirtualizationInterfacesBulkPartialUpdateOK with default headers values
func NewVirtualizationInterfacesBulkPartialUpdateOK() *VirtualizationInterfacesBulkPartialUpdateOK {
	return &VirtualizationInterfacesBulkPartialUpdateOK{}
}

/*
VirtualizationInterfacesBulkPartialUpdateOK describes a response with status code 200, with default header values.

VirtualizationInterfacesBulkPartialUpdateOK virtualization interfaces bulk partial update o k
*/
type VirtualizationInterfacesBulkPartialUpdateOK struct {
	Payload *models.VMInterface
}

// IsSuccess returns true when this virtualization interfaces bulk partial update o k response has a 2xx status code
func (o *VirtualizationInterfacesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization interfaces bulk partial update o k response has a 3xx status code
func (o *VirtualizationInterfacesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization interfaces bulk partial update o k response has a 4xx status code
func (o *VirtualizationInterfacesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization interfaces bulk partial update o k response has a 5xx status code
func (o *VirtualizationInterfacesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization interfaces bulk partial update o k response a status code equal to that given
func (o *VirtualizationInterfacesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the virtualization interfaces bulk partial update o k response
func (o *VirtualizationInterfacesBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *VirtualizationInterfacesBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /virtualization/interfaces/][%d] virtualizationInterfacesBulkPartialUpdateOK %s", 200, payload)
}

func (o *VirtualizationInterfacesBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /virtualization/interfaces/][%d] virtualizationInterfacesBulkPartialUpdateOK %s", 200, payload)
}

func (o *VirtualizationInterfacesBulkPartialUpdateOK) GetPayload() *models.VMInterface {
	return o.Payload
}

func (o *VirtualizationInterfacesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VMInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
