// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// VirtualizationClustersReadReader is a Reader for the VirtualizationClustersRead structure.
type VirtualizationClustersReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationClustersReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationClustersReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /virtualization/clusters/{id}/] virtualization_clusters_read", response, response.Code())
	}
}

// NewVirtualizationClustersReadOK creates a VirtualizationClustersReadOK with default headers values
func NewVirtualizationClustersReadOK() *VirtualizationClustersReadOK {
	return &VirtualizationClustersReadOK{}
}

/*
VirtualizationClustersReadOK describes a response with status code 200, with default header values.

VirtualizationClustersReadOK virtualization clusters read o k
*/
type VirtualizationClustersReadOK struct {
	Payload *models.Cluster
}

// IsSuccess returns true when this virtualization clusters read o k response has a 2xx status code
func (o *VirtualizationClustersReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization clusters read o k response has a 3xx status code
func (o *VirtualizationClustersReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization clusters read o k response has a 4xx status code
func (o *VirtualizationClustersReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization clusters read o k response has a 5xx status code
func (o *VirtualizationClustersReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization clusters read o k response a status code equal to that given
func (o *VirtualizationClustersReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the virtualization clusters read o k response
func (o *VirtualizationClustersReadOK) Code() int {
	return 200
}

func (o *VirtualizationClustersReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/clusters/{id}/][%d] virtualizationClustersReadOK %s", 200, payload)
}

func (o *VirtualizationClustersReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/clusters/{id}/][%d] virtualizationClustersReadOK %s", 200, payload)
}

func (o *VirtualizationClustersReadOK) GetPayload() *models.Cluster {
	return o.Payload
}

func (o *VirtualizationClustersReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
