// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// VirtualizationVirtualDisksListReader is a Reader for the VirtualizationVirtualDisksList structure.
type VirtualizationVirtualDisksListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationVirtualDisksListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationVirtualDisksListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVirtualizationVirtualDisksListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVirtualizationVirtualDisksListOK creates a VirtualizationVirtualDisksListOK with default headers values
func NewVirtualizationVirtualDisksListOK() *VirtualizationVirtualDisksListOK {
	return &VirtualizationVirtualDisksListOK{}
}

/*
VirtualizationVirtualDisksListOK describes a response with status code 200, with default header values.

VirtualizationVirtualDisksListOK virtualization virtual disks list o k
*/
type VirtualizationVirtualDisksListOK struct {
	Payload *VirtualizationVirtualDisksListOKBody
}

// IsSuccess returns true when this virtualization virtual disks list o k response has a 2xx status code
func (o *VirtualizationVirtualDisksListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization virtual disks list o k response has a 3xx status code
func (o *VirtualizationVirtualDisksListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization virtual disks list o k response has a 4xx status code
func (o *VirtualizationVirtualDisksListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization virtual disks list o k response has a 5xx status code
func (o *VirtualizationVirtualDisksListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization virtual disks list o k response a status code equal to that given
func (o *VirtualizationVirtualDisksListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the virtualization virtual disks list o k response
func (o *VirtualizationVirtualDisksListOK) Code() int {
	return 200
}

func (o *VirtualizationVirtualDisksListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/virtual-disks/][%d] virtualizationVirtualDisksListOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/virtual-disks/][%d] virtualizationVirtualDisksListOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksListOK) GetPayload() *VirtualizationVirtualDisksListOKBody {
	return o.Payload
}

func (o *VirtualizationVirtualDisksListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(VirtualizationVirtualDisksListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualizationVirtualDisksListDefault creates a VirtualizationVirtualDisksListDefault with default headers values
func NewVirtualizationVirtualDisksListDefault(code int) *VirtualizationVirtualDisksListDefault {
	return &VirtualizationVirtualDisksListDefault{
		_statusCode: code,
	}
}

/*
VirtualizationVirtualDisksListDefault describes a response with status code -1, with default header values.

VirtualizationVirtualDisksListDefault virtualization virtual disks list default
*/
type VirtualizationVirtualDisksListDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this virtualization virtual disks list default response has a 2xx status code
func (o *VirtualizationVirtualDisksListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this virtualization virtual disks list default response has a 3xx status code
func (o *VirtualizationVirtualDisksListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this virtualization virtual disks list default response has a 4xx status code
func (o *VirtualizationVirtualDisksListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this virtualization virtual disks list default response has a 5xx status code
func (o *VirtualizationVirtualDisksListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this virtualization virtual disks list default response a status code equal to that given
func (o *VirtualizationVirtualDisksListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the virtualization virtual disks list default response
func (o *VirtualizationVirtualDisksListDefault) Code() int {
	return o._statusCode
}

func (o *VirtualizationVirtualDisksListDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/virtual-disks/][%d] virtualization_virtual-disks_list default %s", o._statusCode, payload)
}

func (o *VirtualizationVirtualDisksListDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtualization/virtual-disks/][%d] virtualization_virtual-disks_list default %s", o._statusCode, payload)
}

func (o *VirtualizationVirtualDisksListDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationVirtualDisksListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
VirtualizationVirtualDisksListOKBody virtualization virtual disks list o k body
swagger:model VirtualizationVirtualDisksListOKBody
*/
type VirtualizationVirtualDisksListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.VirtualDisk `json:"results"`
}

// Validate validates this virtualization virtual disks list o k body
func (o *VirtualizationVirtualDisksListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VirtualizationVirtualDisksListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("virtualizationVirtualDisksListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *VirtualizationVirtualDisksListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("virtualizationVirtualDisksListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *VirtualizationVirtualDisksListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("virtualizationVirtualDisksListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *VirtualizationVirtualDisksListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("virtualizationVirtualDisksListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("virtualizationVirtualDisksListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("virtualizationVirtualDisksListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this virtualization virtual disks list o k body based on the context it is used
func (o *VirtualizationVirtualDisksListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *VirtualizationVirtualDisksListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {

			if swag.IsZero(o.Results[i]) { // not required
				return nil
			}

			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("virtualizationVirtualDisksListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("virtualizationVirtualDisksListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *VirtualizationVirtualDisksListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *VirtualizationVirtualDisksListOKBody) UnmarshalBinary(b []byte) error {
	var res VirtualizationVirtualDisksListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
