// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CircuitsProvidersBulkDeleteReader is a Reader for the CircuitsProvidersBulkDelete structure.
type CircuitsProvidersBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsProvidersBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCircuitsProvidersBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /circuits/providers/] circuits_providers_bulk_delete", response, response.Code())
	}
}

// NewCircuitsProvidersBulkDeleteNoContent creates a CircuitsProvidersBulkDeleteNoContent with default headers values
func NewCircuitsProvidersBulkDeleteNoContent() *CircuitsProvidersBulkDeleteNoContent {
	return &CircuitsProvidersBulkDeleteNoContent{}
}

/*
CircuitsProvidersBulkDeleteNoContent describes a response with status code 204, with default header values.

CircuitsProvidersBulkDeleteNoContent circuits providers bulk delete no content
*/
type CircuitsProvidersBulkDeleteNoContent struct {
}

// IsSuccess returns true when this circuits providers bulk delete no content response has a 2xx status code
func (o *CircuitsProvidersBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits providers bulk delete no content response has a 3xx status code
func (o *CircuitsProvidersBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits providers bulk delete no content response has a 4xx status code
func (o *CircuitsProvidersBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits providers bulk delete no content response has a 5xx status code
func (o *CircuitsProvidersBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits providers bulk delete no content response a status code equal to that given
func (o *CircuitsProvidersBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the circuits providers bulk delete no content response
func (o *CircuitsProvidersBulkDeleteNoContent) Code() int {
	return 204
}

func (o *CircuitsProvidersBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /circuits/providers/][%d] circuitsProvidersBulkDeleteNoContent", 204)
}

func (o *CircuitsProvidersBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /circuits/providers/][%d] circuitsProvidersBulkDeleteNoContent", 204)
}

func (o *CircuitsProvidersBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
