// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// CircuitsCircuitTerminationsUpdateReader is a Reader for the CircuitsCircuitTerminationsUpdate structure.
type CircuitsCircuitTerminationsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsCircuitTerminationsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCircuitsCircuitTerminationsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /circuits/circuit-terminations/{id}/] circuits_circuit-terminations_update", response, response.Code())
	}
}

// NewCircuitsCircuitTerminationsUpdateOK creates a CircuitsCircuitTerminationsUpdateOK with default headers values
func NewCircuitsCircuitTerminationsUpdateOK() *CircuitsCircuitTerminationsUpdateOK {
	return &CircuitsCircuitTerminationsUpdateOK{}
}

/*
CircuitsCircuitTerminationsUpdateOK describes a response with status code 200, with default header values.

CircuitsCircuitTerminationsUpdateOK circuits circuit terminations update o k
*/
type CircuitsCircuitTerminationsUpdateOK struct {
	Payload *models.CircuitTermination
}

// IsSuccess returns true when this circuits circuit terminations update o k response has a 2xx status code
func (o *CircuitsCircuitTerminationsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits circuit terminations update o k response has a 3xx status code
func (o *CircuitsCircuitTerminationsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits circuit terminations update o k response has a 4xx status code
func (o *CircuitsCircuitTerminationsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits circuit terminations update o k response has a 5xx status code
func (o *CircuitsCircuitTerminationsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits circuit terminations update o k response a status code equal to that given
func (o *CircuitsCircuitTerminationsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the circuits circuit terminations update o k response
func (o *CircuitsCircuitTerminationsUpdateOK) Code() int {
	return 200
}

func (o *CircuitsCircuitTerminationsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /circuits/circuit-terminations/{id}/][%d] circuitsCircuitTerminationsUpdateOK %s", 200, payload)
}

func (o *CircuitsCircuitTerminationsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /circuits/circuit-terminations/{id}/][%d] circuitsCircuitTerminationsUpdateOK %s", 200, payload)
}

func (o *CircuitsCircuitTerminationsUpdateOK) GetPayload() *models.CircuitTermination {
	return o.Payload
}

func (o *CircuitsCircuitTerminationsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CircuitTermination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
