// Code generated by go-swagger; DO NOT EDIT.

package tenancy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// TenancyTenantsCreateReader is a Reader for the TenancyTenantsCreate structure.
type TenancyTenantsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TenancyTenantsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewTenancyTenantsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /tenancy/tenants/] tenancy_tenants_create", response, response.Code())
	}
}

// NewTenancyTenantsCreateCreated creates a TenancyTenantsCreateCreated with default headers values
func NewTenancyTenantsCreateCreated() *TenancyTenantsCreateCreated {
	return &TenancyTenantsCreateCreated{}
}

/*
TenancyTenantsCreateCreated describes a response with status code 201, with default header values.

TenancyTenantsCreateCreated tenancy tenants create created
*/
type TenancyTenantsCreateCreated struct {
	Payload *models.Tenant
}

// IsSuccess returns true when this tenancy tenants create created response has a 2xx status code
func (o *TenancyTenantsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this tenancy tenants create created response has a 3xx status code
func (o *TenancyTenantsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this tenancy tenants create created response has a 4xx status code
func (o *TenancyTenantsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this tenancy tenants create created response has a 5xx status code
func (o *TenancyTenantsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this tenancy tenants create created response a status code equal to that given
func (o *TenancyTenantsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the tenancy tenants create created response
func (o *TenancyTenantsCreateCreated) Code() int {
	return 201
}

func (o *TenancyTenantsCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenancy/tenants/][%d] tenancyTenantsCreateCreated %s", 201, payload)
}

func (o *TenancyTenantsCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /tenancy/tenants/][%d] tenancyTenantsCreateCreated %s", 201, payload)
}

func (o *TenancyTenantsCreateCreated) GetPayload() *models.Tenant {
	return o.Payload
}

func (o *TenancyTenantsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tenant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
