// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// VpnTunnelGroupsDeleteReader is a Reader for the VpnTunnelGroupsDelete structure.
type VpnTunnelGroupsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VpnTunnelGroupsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewVpnTunnelGroupsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVpnTunnelGroupsDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVpnTunnelGroupsDeleteNoContent creates a VpnTunnelGroupsDeleteNoContent with default headers values
func NewVpnTunnelGroupsDeleteNoContent() *VpnTunnelGroupsDeleteNoContent {
	return &VpnTunnelGroupsDeleteNoContent{}
}

/*
VpnTunnelGroupsDeleteNoContent describes a response with status code 204, with default header values.

VpnTunnelGroupsDeleteNoContent vpn tunnel groups delete no content
*/
type VpnTunnelGroupsDeleteNoContent struct {
}

// IsSuccess returns true when this vpn tunnel groups delete no content response has a 2xx status code
func (o *VpnTunnelGroupsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vpn tunnel groups delete no content response has a 3xx status code
func (o *VpnTunnelGroupsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vpn tunnel groups delete no content response has a 4xx status code
func (o *VpnTunnelGroupsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this vpn tunnel groups delete no content response has a 5xx status code
func (o *VpnTunnelGroupsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this vpn tunnel groups delete no content response a status code equal to that given
func (o *VpnTunnelGroupsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the vpn tunnel groups delete no content response
func (o *VpnTunnelGroupsDeleteNoContent) Code() int {
	return 204
}

func (o *VpnTunnelGroupsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /vpn/tunnel-groups/{id}/][%d] vpnTunnelGroupsDeleteNoContent ", 204)
}

func (o *VpnTunnelGroupsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /vpn/tunnel-groups/{id}/][%d] vpnTunnelGroupsDeleteNoContent ", 204)
}

func (o *VpnTunnelGroupsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVpnTunnelGroupsDeleteDefault creates a VpnTunnelGroupsDeleteDefault with default headers values
func NewVpnTunnelGroupsDeleteDefault(code int) *VpnTunnelGroupsDeleteDefault {
	return &VpnTunnelGroupsDeleteDefault{
		_statusCode: code,
	}
}

/*
VpnTunnelGroupsDeleteDefault describes a response with status code -1, with default header values.

VpnTunnelGroupsDeleteDefault vpn tunnel groups delete default
*/
type VpnTunnelGroupsDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this vpn tunnel groups delete default response has a 2xx status code
func (o *VpnTunnelGroupsDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vpn tunnel groups delete default response has a 3xx status code
func (o *VpnTunnelGroupsDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vpn tunnel groups delete default response has a 4xx status code
func (o *VpnTunnelGroupsDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vpn tunnel groups delete default response has a 5xx status code
func (o *VpnTunnelGroupsDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vpn tunnel groups delete default response a status code equal to that given
func (o *VpnTunnelGroupsDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the vpn tunnel groups delete default response
func (o *VpnTunnelGroupsDeleteDefault) Code() int {
	return o._statusCode
}

func (o *VpnTunnelGroupsDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /vpn/tunnel-groups/{id}/][%d] vpn_tunnel-groups_delete default  %+v", o._statusCode, o.Payload)
}

func (o *VpnTunnelGroupsDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /vpn/tunnel-groups/{id}/][%d] vpn_tunnel-groups_delete default  %+v", o._statusCode, o.Payload)
}

func (o *VpnTunnelGroupsDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VpnTunnelGroupsDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
