// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// NewVpnTunnelGroupsCreateParams creates a new VpnTunnelGroupsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVpnTunnelGroupsCreateParams() *VpnTunnelGroupsCreateParams {
	return &VpnTunnelGroupsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVpnTunnelGroupsCreateParamsWithTimeout creates a new VpnTunnelGroupsCreateParams object
// with the ability to set a timeout on a request.
func NewVpnTunnelGroupsCreateParamsWithTimeout(timeout time.Duration) *VpnTunnelGroupsCreateParams {
	return &VpnTunnelGroupsCreateParams{
		timeout: timeout,
	}
}

// NewVpnTunnelGroupsCreateParamsWithContext creates a new VpnTunnelGroupsCreateParams object
// with the ability to set a context for a request.
func NewVpnTunnelGroupsCreateParamsWithContext(ctx context.Context) *VpnTunnelGroupsCreateParams {
	return &VpnTunnelGroupsCreateParams{
		Context: ctx,
	}
}

// NewVpnTunnelGroupsCreateParamsWithHTTPClient creates a new VpnTunnelGroupsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVpnTunnelGroupsCreateParamsWithHTTPClient(client *http.Client) *VpnTunnelGroupsCreateParams {
	return &VpnTunnelGroupsCreateParams{
		HTTPClient: client,
	}
}

/*
VpnTunnelGroupsCreateParams contains all the parameters to send to the API endpoint

	for the vpn tunnel groups create operation.

	Typically these are written to a http.Request.
*/
type VpnTunnelGroupsCreateParams struct {

	// Data.
	Data *models.TunnelGroup

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vpn tunnel groups create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnTunnelGroupsCreateParams) WithDefaults() *VpnTunnelGroupsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vpn tunnel groups create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VpnTunnelGroupsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) WithTimeout(timeout time.Duration) *VpnTunnelGroupsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) WithContext(ctx context.Context) *VpnTunnelGroupsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) WithHTTPClient(client *http.Client) *VpnTunnelGroupsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) WithData(data *models.TunnelGroup) *VpnTunnelGroupsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the vpn tunnel groups create params
func (o *VpnTunnelGroupsCreateParams) SetData(data *models.TunnelGroup) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *VpnTunnelGroupsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
