// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// VpnTunnelsReadReader is a Reader for the VpnTunnelsRead structure.
type VpnTunnelsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VpnTunnelsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVpnTunnelsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVpnTunnelsReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVpnTunnelsReadOK creates a VpnTunnelsReadOK with default headers values
func NewVpnTunnelsReadOK() *VpnTunnelsReadOK {
	return &VpnTunnelsReadOK{}
}

/*
VpnTunnelsReadOK describes a response with status code 200, with default header values.

VpnTunnelsReadOK vpn tunnels read o k
*/
type VpnTunnelsReadOK struct {
	Payload *models.Tunnel
}

// IsSuccess returns true when this vpn tunnels read o k response has a 2xx status code
func (o *VpnTunnelsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vpn tunnels read o k response has a 3xx status code
func (o *VpnTunnelsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vpn tunnels read o k response has a 4xx status code
func (o *VpnTunnelsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vpn tunnels read o k response has a 5xx status code
func (o *VpnTunnelsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vpn tunnels read o k response a status code equal to that given
func (o *VpnTunnelsReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the vpn tunnels read o k response
func (o *VpnTunnelsReadOK) Code() int {
	return 200
}

func (o *VpnTunnelsReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/tunnels/{id}/][%d] vpnTunnelsReadOK %s", 200, payload)
}

func (o *VpnTunnelsReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/tunnels/{id}/][%d] vpnTunnelsReadOK %s", 200, payload)
}

func (o *VpnTunnelsReadOK) GetPayload() *models.Tunnel {
	return o.Payload
}

func (o *VpnTunnelsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tunnel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVpnTunnelsReadDefault creates a VpnTunnelsReadDefault with default headers values
func NewVpnTunnelsReadDefault(code int) *VpnTunnelsReadDefault {
	return &VpnTunnelsReadDefault{
		_statusCode: code,
	}
}

/*
VpnTunnelsReadDefault describes a response with status code -1, with default header values.

VpnTunnelsReadDefault vpn tunnels read default
*/
type VpnTunnelsReadDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this vpn tunnels read default response has a 2xx status code
func (o *VpnTunnelsReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this vpn tunnels read default response has a 3xx status code
func (o *VpnTunnelsReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this vpn tunnels read default response has a 4xx status code
func (o *VpnTunnelsReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this vpn tunnels read default response has a 5xx status code
func (o *VpnTunnelsReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this vpn tunnels read default response a status code equal to that given
func (o *VpnTunnelsReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the vpn tunnels read default response
func (o *VpnTunnelsReadDefault) Code() int {
	return o._statusCode
}

func (o *VpnTunnelsReadDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/tunnels/{id}/][%d] vpn_tunnels_read default %s", o._statusCode, payload)
}

func (o *VpnTunnelsReadDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vpn/tunnels/{id}/][%d] vpn_tunnels_read default %s", o._statusCode, payload)
}

func (o *VpnTunnelsReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VpnTunnelsReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
