// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// IpamVlanGroupsReadReader is a Reader for the IpamVlanGroupsRead structure.
type IpamVlanGroupsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVlanGroupsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamVlanGroupsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ipam/vlan-groups/{id}/] ipam_vlan-groups_read", response, response.Code())
	}
}

// NewIpamVlanGroupsReadOK creates a IpamVlanGroupsReadOK with default headers values
func NewIpamVlanGroupsReadOK() *IpamVlanGroupsReadOK {
	return &IpamVlanGroupsReadOK{}
}

/*
IpamVlanGroupsReadOK describes a response with status code 200, with default header values.

IpamVlanGroupsReadOK ipam vlan groups read o k
*/
type IpamVlanGroupsReadOK struct {
	Payload *models.VLANGroup
}

// IsSuccess returns true when this ipam vlan groups read o k response has a 2xx status code
func (o *IpamVlanGroupsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vlan groups read o k response has a 3xx status code
func (o *IpamVlanGroupsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vlan groups read o k response has a 4xx status code
func (o *IpamVlanGroupsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vlan groups read o k response has a 5xx status code
func (o *IpamVlanGroupsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vlan groups read o k response a status code equal to that given
func (o *IpamVlanGroupsReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ipam vlan groups read o k response
func (o *IpamVlanGroupsReadOK) Code() int {
	return 200
}

func (o *IpamVlanGroupsReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/vlan-groups/{id}/][%d] ipamVlanGroupsReadOK %s", 200, payload)
}

func (o *IpamVlanGroupsReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/vlan-groups/{id}/][%d] ipamVlanGroupsReadOK %s", 200, payload)
}

func (o *IpamVlanGroupsReadOK) GetPayload() *models.VLANGroup {
	return o.Payload
}

func (o *IpamVlanGroupsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VLANGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
