// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// IpamServicesBulkPartialUpdateReader is a Reader for the IpamServicesBulkPartialUpdate structure.
type IpamServicesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamServicesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamServicesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /ipam/services/] ipam_services_bulk_partial_update", response, response.Code())
	}
}

// NewIpamServicesBulkPartialUpdateOK creates a IpamServicesBulkPartialUpdateOK with default headers values
func NewIpamServicesBulkPartialUpdateOK() *IpamServicesBulkPartialUpdateOK {
	return &IpamServicesBulkPartialUpdateOK{}
}

/*
IpamServicesBulkPartialUpdateOK describes a response with status code 200, with default header values.

IpamServicesBulkPartialUpdateOK ipam services bulk partial update o k
*/
type IpamServicesBulkPartialUpdateOK struct {
	Payload *models.Service
}

// IsSuccess returns true when this ipam services bulk partial update o k response has a 2xx status code
func (o *IpamServicesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam services bulk partial update o k response has a 3xx status code
func (o *IpamServicesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam services bulk partial update o k response has a 4xx status code
func (o *IpamServicesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam services bulk partial update o k response has a 5xx status code
func (o *IpamServicesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam services bulk partial update o k response a status code equal to that given
func (o *IpamServicesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ipam services bulk partial update o k response
func (o *IpamServicesBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *IpamServicesBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /ipam/services/][%d] ipamServicesBulkPartialUpdateOK %s", 200, payload)
}

func (o *IpamServicesBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /ipam/services/][%d] ipamServicesBulkPartialUpdateOK %s", 200, payload)
}

func (o *IpamServicesBulkPartialUpdateOK) GetPayload() *models.Service {
	return o.Payload
}

func (o *IpamServicesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Service)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
