// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// IpamRouteTargetsBulkPartialUpdateReader is a Reader for the IpamRouteTargetsBulkPartialUpdate structure.
type IpamRouteTargetsBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRouteTargetsBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRouteTargetsBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /ipam/route-targets/] ipam_route-targets_bulk_partial_update", response, response.Code())
	}
}

// NewIpamRouteTargetsBulkPartialUpdateOK creates a IpamRouteTargetsBulkPartialUpdateOK with default headers values
func NewIpamRouteTargetsBulkPartialUpdateOK() *IpamRouteTargetsBulkPartialUpdateOK {
	return &IpamRouteTargetsBulkPartialUpdateOK{}
}

/*
IpamRouteTargetsBulkPartialUpdateOK describes a response with status code 200, with default header values.

IpamRouteTargetsBulkPartialUpdateOK ipam route targets bulk partial update o k
*/
type IpamRouteTargetsBulkPartialUpdateOK struct {
	Payload *models.RouteTarget
}

// IsSuccess returns true when this ipam route targets bulk partial update o k response has a 2xx status code
func (o *IpamRouteTargetsBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam route targets bulk partial update o k response has a 3xx status code
func (o *IpamRouteTargetsBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam route targets bulk partial update o k response has a 4xx status code
func (o *IpamRouteTargetsBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam route targets bulk partial update o k response has a 5xx status code
func (o *IpamRouteTargetsBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam route targets bulk partial update o k response a status code equal to that given
func (o *IpamRouteTargetsBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ipam route targets bulk partial update o k response
func (o *IpamRouteTargetsBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *IpamRouteTargetsBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /ipam/route-targets/][%d] ipamRouteTargetsBulkPartialUpdateOK %s", 200, payload)
}

func (o *IpamRouteTargetsBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /ipam/route-targets/][%d] ipamRouteTargetsBulkPartialUpdateOK %s", 200, payload)
}

func (o *IpamRouteTargetsBulkPartialUpdateOK) GetPayload() *models.RouteTarget {
	return o.Payload
}

func (o *IpamRouteTargetsBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteTarget)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
