// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// IpamRouteTargetsReadReader is a Reader for the IpamRouteTargetsRead structure.
type IpamRouteTargetsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamRouteTargetsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamRouteTargetsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ipam/route-targets/{id}/] ipam_route-targets_read", response, response.Code())
	}
}

// NewIpamRouteTargetsReadOK creates a IpamRouteTargetsReadOK with default headers values
func NewIpamRouteTargetsReadOK() *IpamRouteTargetsReadOK {
	return &IpamRouteTargetsReadOK{}
}

/*
IpamRouteTargetsReadOK describes a response with status code 200, with default header values.

IpamRouteTargetsReadOK ipam route targets read o k
*/
type IpamRouteTargetsReadOK struct {
	Payload *models.RouteTarget
}

// IsSuccess returns true when this ipam route targets read o k response has a 2xx status code
func (o *IpamRouteTargetsReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam route targets read o k response has a 3xx status code
func (o *IpamRouteTargetsReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam route targets read o k response has a 4xx status code
func (o *IpamRouteTargetsReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam route targets read o k response has a 5xx status code
func (o *IpamRouteTargetsReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam route targets read o k response a status code equal to that given
func (o *IpamRouteTargetsReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ipam route targets read o k response
func (o *IpamRouteTargetsReadOK) Code() int {
	return 200
}

func (o *IpamRouteTargetsReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadOK %s", 200, payload)
}

func (o *IpamRouteTargetsReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/route-targets/{id}/][%d] ipamRouteTargetsReadOK %s", 200, payload)
}

func (o *IpamRouteTargetsReadOK) GetPayload() *models.RouteTarget {
	return o.Payload
}

func (o *IpamRouteTargetsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteTarget)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
