// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// NewVirtualizationVirtualDisksBulkPartialUpdateParams creates a new VirtualizationVirtualDisksBulkPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVirtualizationVirtualDisksBulkPartialUpdateParams() *VirtualizationVirtualDisksBulkPartialUpdateParams {
	return &VirtualizationVirtualDisksBulkPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithTimeout creates a new VirtualizationVirtualDisksBulkPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithTimeout(timeout time.Duration) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	return &VirtualizationVirtualDisksBulkPartialUpdateParams{
		timeout: timeout,
	}
}

// NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithContext creates a new VirtualizationVirtualDisksBulkPartialUpdateParams object
// with the ability to set a context for a request.
func NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithContext(ctx context.Context) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	return &VirtualizationVirtualDisksBulkPartialUpdateParams{
		Context: ctx,
	}
}

// NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithHTTPClient creates a new VirtualizationVirtualDisksBulkPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVirtualizationVirtualDisksBulkPartialUpdateParamsWithHTTPClient(client *http.Client) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	return &VirtualizationVirtualDisksBulkPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
VirtualizationVirtualDisksBulkPartialUpdateParams contains all the parameters to send to the API endpoint

	for the virtualization virtual disks bulk partial update operation.

	Typically these are written to a http.Request.
*/
type VirtualizationVirtualDisksBulkPartialUpdateParams struct {

	// Data.
	Data *models.WritableVirtualDisk

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the virtualization virtual disks bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WithDefaults() *VirtualizationVirtualDisksBulkPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the virtualization virtual disks bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WithTimeout(timeout time.Duration) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WithContext(ctx context.Context) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WithHTTPClient(client *http.Client) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WithData(data *models.WritableVirtualDisk) *VirtualizationVirtualDisksBulkPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the virtualization virtual disks bulk partial update params
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) SetData(data *models.WritableVirtualDisk) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualizationVirtualDisksBulkPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
