// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// VirtualizationVirtualDisksBulkUpdateReader is a Reader for the VirtualizationVirtualDisksBulkUpdate structure.
type VirtualizationVirtualDisksBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationVirtualDisksBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationVirtualDisksBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /virtualization/virtual-disks/] virtualization_virtual-disks_bulk_update", response, response.Code())
	}
}

// NewVirtualizationVirtualDisksBulkUpdateOK creates a VirtualizationVirtualDisksBulkUpdateOK with default headers values
func NewVirtualizationVirtualDisksBulkUpdateOK() *VirtualizationVirtualDisksBulkUpdateOK {
	return &VirtualizationVirtualDisksBulkUpdateOK{}
}

/*
VirtualizationVirtualDisksBulkUpdateOK describes a response with status code 200, with default header values.

VirtualizationVirtualDisksBulkUpdateOK virtualization virtual disks bulk update o k
*/
type VirtualizationVirtualDisksBulkUpdateOK struct {
	Payload *models.VirtualDisk
}

// IsSuccess returns true when this virtualization virtual disks bulk update o k response has a 2xx status code
func (o *VirtualizationVirtualDisksBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization virtual disks bulk update o k response has a 3xx status code
func (o *VirtualizationVirtualDisksBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization virtual disks bulk update o k response has a 4xx status code
func (o *VirtualizationVirtualDisksBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization virtual disks bulk update o k response has a 5xx status code
func (o *VirtualizationVirtualDisksBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization virtual disks bulk update o k response a status code equal to that given
func (o *VirtualizationVirtualDisksBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the virtualization virtual disks bulk update o k response
func (o *VirtualizationVirtualDisksBulkUpdateOK) Code() int {
	return 200
}

func (o *VirtualizationVirtualDisksBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /virtualization/virtual-disks/][%d] virtualizationVirtualDisksBulkUpdateOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /virtualization/virtual-disks/][%d] virtualizationVirtualDisksBulkUpdateOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksBulkUpdateOK) GetPayload() *models.VirtualDisk {
	return o.Payload
}

func (o *VirtualizationVirtualDisksBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualDisk)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
