// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// VirtualizationVirtualDisksUpdateReader is a Reader for the VirtualizationVirtualDisksUpdate structure.
type VirtualizationVirtualDisksUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationVirtualDisksUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVirtualizationVirtualDisksUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /virtualization/virtual-disks/{id}/] virtualization_virtual-disks_update", response, response.Code())
	}
}

// NewVirtualizationVirtualDisksUpdateOK creates a VirtualizationVirtualDisksUpdateOK with default headers values
func NewVirtualizationVirtualDisksUpdateOK() *VirtualizationVirtualDisksUpdateOK {
	return &VirtualizationVirtualDisksUpdateOK{}
}

/*
VirtualizationVirtualDisksUpdateOK describes a response with status code 200, with default header values.

VirtualizationVirtualDisksUpdateOK virtualization virtual disks update o k
*/
type VirtualizationVirtualDisksUpdateOK struct {
	Payload *models.VirtualDisk
}

// IsSuccess returns true when this virtualization virtual disks update o k response has a 2xx status code
func (o *VirtualizationVirtualDisksUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this virtualization virtual disks update o k response has a 3xx status code
func (o *VirtualizationVirtualDisksUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this virtualization virtual disks update o k response has a 4xx status code
func (o *VirtualizationVirtualDisksUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this virtualization virtual disks update o k response has a 5xx status code
func (o *VirtualizationVirtualDisksUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this virtualization virtual disks update o k response a status code equal to that given
func (o *VirtualizationVirtualDisksUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the virtualization virtual disks update o k response
func (o *VirtualizationVirtualDisksUpdateOK) Code() int {
	return 200
}

func (o *VirtualizationVirtualDisksUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /virtualization/virtual-disks/{id}/][%d] virtualizationVirtualDisksUpdateOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /virtualization/virtual-disks/{id}/][%d] virtualizationVirtualDisksUpdateOK %s", 200, payload)
}

func (o *VirtualizationVirtualDisksUpdateOK) GetPayload() *models.VirtualDisk {
	return o.Payload
}

func (o *VirtualizationVirtualDisksUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualDisk)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
