// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// ExtrasExportTemplatesCreateReader is a Reader for the ExtrasExportTemplatesCreate structure.
type ExtrasExportTemplatesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasExportTemplatesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewExtrasExportTemplatesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /extras/export-templates/] extras_export-templates_create", response, response.Code())
	}
}

// NewExtrasExportTemplatesCreateCreated creates a ExtrasExportTemplatesCreateCreated with default headers values
func NewExtrasExportTemplatesCreateCreated() *ExtrasExportTemplatesCreateCreated {
	return &ExtrasExportTemplatesCreateCreated{}
}

/*
ExtrasExportTemplatesCreateCreated describes a response with status code 201, with default header values.

ExtrasExportTemplatesCreateCreated extras export templates create created
*/
type ExtrasExportTemplatesCreateCreated struct {
	Payload *models.ExportTemplate
}

// IsSuccess returns true when this extras export templates create created response has a 2xx status code
func (o *ExtrasExportTemplatesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras export templates create created response has a 3xx status code
func (o *ExtrasExportTemplatesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras export templates create created response has a 4xx status code
func (o *ExtrasExportTemplatesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras export templates create created response has a 5xx status code
func (o *ExtrasExportTemplatesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this extras export templates create created response a status code equal to that given
func (o *ExtrasExportTemplatesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the extras export templates create created response
func (o *ExtrasExportTemplatesCreateCreated) Code() int {
	return 201
}

func (o *ExtrasExportTemplatesCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/][%d] extrasExportTemplatesCreateCreated %s", 201, payload)
}

func (o *ExtrasExportTemplatesCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /extras/export-templates/][%d] extrasExportTemplatesCreateCreated %s", 201, payload)
}

func (o *ExtrasExportTemplatesCreateCreated) GetPayload() *models.ExportTemplate {
	return o.Payload
}

func (o *ExtrasExportTemplatesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExportTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
