// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasExportTemplatesDeleteReader is a Reader for the ExtrasExportTemplatesDelete structure.
type ExtrasExportTemplatesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasExportTemplatesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExtrasExportTemplatesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /extras/export-templates/{id}/] extras_export-templates_delete", response, response.Code())
	}
}

// NewExtrasExportTemplatesDeleteNoContent creates a ExtrasExportTemplatesDeleteNoContent with default headers values
func NewExtrasExportTemplatesDeleteNoContent() *ExtrasExportTemplatesDeleteNoContent {
	return &ExtrasExportTemplatesDeleteNoContent{}
}

/*
ExtrasExportTemplatesDeleteNoContent describes a response with status code 204, with default header values.

ExtrasExportTemplatesDeleteNoContent extras export templates delete no content
*/
type ExtrasExportTemplatesDeleteNoContent struct {
}

// IsSuccess returns true when this extras export templates delete no content response has a 2xx status code
func (o *ExtrasExportTemplatesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras export templates delete no content response has a 3xx status code
func (o *ExtrasExportTemplatesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras export templates delete no content response has a 4xx status code
func (o *ExtrasExportTemplatesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras export templates delete no content response has a 5xx status code
func (o *ExtrasExportTemplatesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this extras export templates delete no content response a status code equal to that given
func (o *ExtrasExportTemplatesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the extras export templates delete no content response
func (o *ExtrasExportTemplatesDeleteNoContent) Code() int {
	return 204
}

func (o *ExtrasExportTemplatesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /extras/export-templates/{id}/][%d] extrasExportTemplatesDeleteNoContent", 204)
}

func (o *ExtrasExportTemplatesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /extras/export-templates/{id}/][%d] extrasExportTemplatesDeleteNoContent", 204)
}

func (o *ExtrasExportTemplatesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
