// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CircuitsProviderNetworksBulkDeleteReader is a Reader for the CircuitsProviderNetworksBulkDelete structure.
type CircuitsProviderNetworksBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsProviderNetworksBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCircuitsProviderNetworksBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /circuits/provider-networks/] circuits_provider-networks_bulk_delete", response, response.Code())
	}
}

// NewCircuitsProviderNetworksBulkDeleteNoContent creates a CircuitsProviderNetworksBulkDeleteNoContent with default headers values
func NewCircuitsProviderNetworksBulkDeleteNoContent() *CircuitsProviderNetworksBulkDeleteNoContent {
	return &CircuitsProviderNetworksBulkDeleteNoContent{}
}

/*
CircuitsProviderNetworksBulkDeleteNoContent describes a response with status code 204, with default header values.

CircuitsProviderNetworksBulkDeleteNoContent circuits provider networks bulk delete no content
*/
type CircuitsProviderNetworksBulkDeleteNoContent struct {
}

// IsSuccess returns true when this circuits provider networks bulk delete no content response has a 2xx status code
func (o *CircuitsProviderNetworksBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits provider networks bulk delete no content response has a 3xx status code
func (o *CircuitsProviderNetworksBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits provider networks bulk delete no content response has a 4xx status code
func (o *CircuitsProviderNetworksBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits provider networks bulk delete no content response has a 5xx status code
func (o *CircuitsProviderNetworksBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits provider networks bulk delete no content response a status code equal to that given
func (o *CircuitsProviderNetworksBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the circuits provider networks bulk delete no content response
func (o *CircuitsProviderNetworksBulkDeleteNoContent) Code() int {
	return 204
}

func (o *CircuitsProviderNetworksBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /circuits/provider-networks/][%d] circuitsProviderNetworksBulkDeleteNoContent", 204)
}

func (o *CircuitsProviderNetworksBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /circuits/provider-networks/][%d] circuitsProviderNetworksBulkDeleteNoContent", 204)
}

func (o *CircuitsProviderNetworksBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
