// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// IpamVlanGroupsAvailableVlansListReader is a Reader for the IpamVlanGroupsAvailableVlansList structure.
type IpamVlanGroupsAvailableVlansListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVlanGroupsAvailableVlansListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamVlanGroupsAvailableVlansListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ipam/vlan-groups/{id}/available-vlans/] ipam_vlan-groups_available-vlans_list", response, response.Code())
	}
}

// NewIpamVlanGroupsAvailableVlansListOK creates a IpamVlanGroupsAvailableVlansListOK with default headers values
func NewIpamVlanGroupsAvailableVlansListOK() *IpamVlanGroupsAvailableVlansListOK {
	return &IpamVlanGroupsAvailableVlansListOK{}
}

/*
IpamVlanGroupsAvailableVlansListOK describes a response with status code 200, with default header values.

IpamVlanGroupsAvailableVlansListOK ipam vlan groups available vlans list o k
*/
type IpamVlanGroupsAvailableVlansListOK struct {
	Payload []*models.AvailableVLAN
}

// IsSuccess returns true when this ipam vlan groups available vlans list o k response has a 2xx status code
func (o *IpamVlanGroupsAvailableVlansListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vlan groups available vlans list o k response has a 3xx status code
func (o *IpamVlanGroupsAvailableVlansListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vlan groups available vlans list o k response has a 4xx status code
func (o *IpamVlanGroupsAvailableVlansListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vlan groups available vlans list o k response has a 5xx status code
func (o *IpamVlanGroupsAvailableVlansListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vlan groups available vlans list o k response a status code equal to that given
func (o *IpamVlanGroupsAvailableVlansListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ipam vlan groups available vlans list o k response
func (o *IpamVlanGroupsAvailableVlansListOK) Code() int {
	return 200
}

func (o *IpamVlanGroupsAvailableVlansListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/vlan-groups/{id}/available-vlans/][%d] ipamVlanGroupsAvailableVlansListOK %s", 200, payload)
}

func (o *IpamVlanGroupsAvailableVlansListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ipam/vlan-groups/{id}/available-vlans/][%d] ipamVlanGroupsAvailableVlansListOK %s", 200, payload)
}

func (o *IpamVlanGroupsAvailableVlansListOK) GetPayload() []*models.AvailableVLAN {
	return o.Payload
}

func (o *IpamVlanGroupsAvailableVlansListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
