// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamVlansBulkDeleteReader is a Reader for the IpamVlansBulkDelete structure.
type IpamVlansBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamVlansBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamVlansBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /ipam/vlans/] ipam_vlans_bulk_delete", response, response.Code())
	}
}

// NewIpamVlansBulkDeleteNoContent creates a IpamVlansBulkDeleteNoContent with default headers values
func NewIpamVlansBulkDeleteNoContent() *IpamVlansBulkDeleteNoContent {
	return &IpamVlansBulkDeleteNoContent{}
}

/*
IpamVlansBulkDeleteNoContent describes a response with status code 204, with default header values.

IpamVlansBulkDeleteNoContent ipam vlans bulk delete no content
*/
type IpamVlansBulkDeleteNoContent struct {
}

// IsSuccess returns true when this ipam vlans bulk delete no content response has a 2xx status code
func (o *IpamVlansBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ipam vlans bulk delete no content response has a 3xx status code
func (o *IpamVlansBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ipam vlans bulk delete no content response has a 4xx status code
func (o *IpamVlansBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this ipam vlans bulk delete no content response has a 5xx status code
func (o *IpamVlansBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this ipam vlans bulk delete no content response a status code equal to that given
func (o *IpamVlansBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the ipam vlans bulk delete no content response
func (o *IpamVlansBulkDeleteNoContent) Code() int {
	return 204
}

func (o *IpamVlansBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/vlans/][%d] ipamVlansBulkDeleteNoContent", 204)
}

func (o *IpamVlansBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /ipam/vlans/][%d] ipamVlansBulkDeleteNoContent", 204)
}

func (o *IpamVlansBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
