// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimSiteGroupsBulkUpdateReader is a Reader for the DcimSiteGroupsBulkUpdate structure.
type DcimSiteGroupsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimSiteGroupsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimSiteGroupsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/site-groups/] dcim_site-groups_bulk_update", response, response.Code())
	}
}

// NewDcimSiteGroupsBulkUpdateOK creates a DcimSiteGroupsBulkUpdateOK with default headers values
func NewDcimSiteGroupsBulkUpdateOK() *DcimSiteGroupsBulkUpdateOK {
	return &DcimSiteGroupsBulkUpdateOK{}
}

/*
DcimSiteGroupsBulkUpdateOK describes a response with status code 200, with default header values.

DcimSiteGroupsBulkUpdateOK dcim site groups bulk update o k
*/
type DcimSiteGroupsBulkUpdateOK struct {
	Payload *models.SiteGroup
}

// IsSuccess returns true when this dcim site groups bulk update o k response has a 2xx status code
func (o *DcimSiteGroupsBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim site groups bulk update o k response has a 3xx status code
func (o *DcimSiteGroupsBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim site groups bulk update o k response has a 4xx status code
func (o *DcimSiteGroupsBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim site groups bulk update o k response has a 5xx status code
func (o *DcimSiteGroupsBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim site groups bulk update o k response a status code equal to that given
func (o *DcimSiteGroupsBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim site groups bulk update o k response
func (o *DcimSiteGroupsBulkUpdateOK) Code() int {
	return 200
}

func (o *DcimSiteGroupsBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/site-groups/][%d] dcimSiteGroupsBulkUpdateOK %s", 200, payload)
}

func (o *DcimSiteGroupsBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/site-groups/][%d] dcimSiteGroupsBulkUpdateOK %s", 200, payload)
}

func (o *DcimSiteGroupsBulkUpdateOK) GetPayload() *models.SiteGroup {
	return o.Payload
}

func (o *DcimSiteGroupsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SiteGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
