// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimPowerPanelsDeleteReader is a Reader for the DcimPowerPanelsDelete structure.
type DcimPowerPanelsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPowerPanelsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimPowerPanelsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/power-panels/{id}/] dcim_power-panels_delete", response, response.Code())
	}
}

// NewDcimPowerPanelsDeleteNoContent creates a DcimPowerPanelsDeleteNoContent with default headers values
func NewDcimPowerPanelsDeleteNoContent() *DcimPowerPanelsDeleteNoContent {
	return &DcimPowerPanelsDeleteNoContent{}
}

/*
DcimPowerPanelsDeleteNoContent describes a response with status code 204, with default header values.

DcimPowerPanelsDeleteNoContent dcim power panels delete no content
*/
type DcimPowerPanelsDeleteNoContent struct {
}

// IsSuccess returns true when this dcim power panels delete no content response has a 2xx status code
func (o *DcimPowerPanelsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim power panels delete no content response has a 3xx status code
func (o *DcimPowerPanelsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim power panels delete no content response has a 4xx status code
func (o *DcimPowerPanelsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim power panels delete no content response has a 5xx status code
func (o *DcimPowerPanelsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim power panels delete no content response a status code equal to that given
func (o *DcimPowerPanelsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim power panels delete no content response
func (o *DcimPowerPanelsDeleteNoContent) Code() int {
	return 204
}

func (o *DcimPowerPanelsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/power-panels/{id}/][%d] dcimPowerPanelsDeleteNoContent", 204)
}

func (o *DcimPowerPanelsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/power-panels/{id}/][%d] dcimPowerPanelsDeleteNoContent", 204)
}

func (o *DcimPowerPanelsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
