// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimModulesReadReader is a Reader for the DcimModulesRead structure.
type DcimModulesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimModulesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimModulesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /dcim/modules/{id}/] dcim_modules_read", response, response.Code())
	}
}

// NewDcimModulesReadOK creates a DcimModulesReadOK with default headers values
func NewDcimModulesReadOK() *DcimModulesReadOK {
	return &DcimModulesReadOK{}
}

/*
DcimModulesReadOK describes a response with status code 200, with default header values.

DcimModulesReadOK dcim modules read o k
*/
type DcimModulesReadOK struct {
	Payload *models.Module
}

// IsSuccess returns true when this dcim modules read o k response has a 2xx status code
func (o *DcimModulesReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim modules read o k response has a 3xx status code
func (o *DcimModulesReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim modules read o k response has a 4xx status code
func (o *DcimModulesReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim modules read o k response has a 5xx status code
func (o *DcimModulesReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim modules read o k response a status code equal to that given
func (o *DcimModulesReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim modules read o k response
func (o *DcimModulesReadOK) Code() int {
	return 200
}

func (o *DcimModulesReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/modules/{id}/][%d] dcimModulesReadOK %s", 200, payload)
}

func (o *DcimModulesReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/modules/{id}/][%d] dcimModulesReadOK %s", 200, payload)
}

func (o *DcimModulesReadOK) GetPayload() *models.Module {
	return o.Payload
}

func (o *DcimModulesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Module)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
