// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimRackReservationsPartialUpdateReader is a Reader for the DcimRackReservationsPartialUpdate structure.
type DcimRackReservationsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackReservationsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimRackReservationsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/rack-reservations/{id}/] dcim_rack-reservations_partial_update", response, response.Code())
	}
}

// NewDcimRackReservationsPartialUpdateOK creates a DcimRackReservationsPartialUpdateOK with default headers values
func NewDcimRackReservationsPartialUpdateOK() *DcimRackReservationsPartialUpdateOK {
	return &DcimRackReservationsPartialUpdateOK{}
}

/*
DcimRackReservationsPartialUpdateOK describes a response with status code 200, with default header values.

DcimRackReservationsPartialUpdateOK dcim rack reservations partial update o k
*/
type DcimRackReservationsPartialUpdateOK struct {
	Payload *models.RackReservation
}

// IsSuccess returns true when this dcim rack reservations partial update o k response has a 2xx status code
func (o *DcimRackReservationsPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack reservations partial update o k response has a 3xx status code
func (o *DcimRackReservationsPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack reservations partial update o k response has a 4xx status code
func (o *DcimRackReservationsPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack reservations partial update o k response has a 5xx status code
func (o *DcimRackReservationsPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack reservations partial update o k response a status code equal to that given
func (o *DcimRackReservationsPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim rack reservations partial update o k response
func (o *DcimRackReservationsPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimRackReservationsPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/rack-reservations/{id}/][%d] dcimRackReservationsPartialUpdateOK %s", 200, payload)
}

func (o *DcimRackReservationsPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/rack-reservations/{id}/][%d] dcimRackReservationsPartialUpdateOK %s", 200, payload)
}

func (o *DcimRackReservationsPartialUpdateOK) GetPayload() *models.RackReservation {
	return o.Payload
}

func (o *DcimRackReservationsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RackReservation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
