// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimModuleBayTemplatesPartialUpdateReader is a Reader for the DcimModuleBayTemplatesPartialUpdate structure.
type DcimModuleBayTemplatesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimModuleBayTemplatesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimModuleBayTemplatesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/module-bay-templates/{id}/] dcim_module-bay-templates_partial_update", response, response.Code())
	}
}

// NewDcimModuleBayTemplatesPartialUpdateOK creates a DcimModuleBayTemplatesPartialUpdateOK with default headers values
func NewDcimModuleBayTemplatesPartialUpdateOK() *DcimModuleBayTemplatesPartialUpdateOK {
	return &DcimModuleBayTemplatesPartialUpdateOK{}
}

/*
DcimModuleBayTemplatesPartialUpdateOK describes a response with status code 200, with default header values.

DcimModuleBayTemplatesPartialUpdateOK dcim module bay templates partial update o k
*/
type DcimModuleBayTemplatesPartialUpdateOK struct {
	Payload *models.ModuleBayTemplate
}

// IsSuccess returns true when this dcim module bay templates partial update o k response has a 2xx status code
func (o *DcimModuleBayTemplatesPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim module bay templates partial update o k response has a 3xx status code
func (o *DcimModuleBayTemplatesPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim module bay templates partial update o k response has a 4xx status code
func (o *DcimModuleBayTemplatesPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim module bay templates partial update o k response has a 5xx status code
func (o *DcimModuleBayTemplatesPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim module bay templates partial update o k response a status code equal to that given
func (o *DcimModuleBayTemplatesPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim module bay templates partial update o k response
func (o *DcimModuleBayTemplatesPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimModuleBayTemplatesPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/module-bay-templates/{id}/][%d] dcimModuleBayTemplatesPartialUpdateOK %s", 200, payload)
}

func (o *DcimModuleBayTemplatesPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/module-bay-templates/{id}/][%d] dcimModuleBayTemplatesPartialUpdateOK %s", 200, payload)
}

func (o *DcimModuleBayTemplatesPartialUpdateOK) GetPayload() *models.ModuleBayTemplate {
	return o.Payload
}

func (o *DcimModuleBayTemplatesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModuleBayTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
