// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimInventoryItemsPartialUpdateReader is a Reader for the DcimInventoryItemsPartialUpdate structure.
type DcimInventoryItemsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInventoryItemsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInventoryItemsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/inventory-items/{id}/] dcim_inventory-items_partial_update", response, response.Code())
	}
}

// NewDcimInventoryItemsPartialUpdateOK creates a DcimInventoryItemsPartialUpdateOK with default headers values
func NewDcimInventoryItemsPartialUpdateOK() *DcimInventoryItemsPartialUpdateOK {
	return &DcimInventoryItemsPartialUpdateOK{}
}

/*
DcimInventoryItemsPartialUpdateOK describes a response with status code 200, with default header values.

DcimInventoryItemsPartialUpdateOK dcim inventory items partial update o k
*/
type DcimInventoryItemsPartialUpdateOK struct {
	Payload *models.InventoryItem
}

// IsSuccess returns true when this dcim inventory items partial update o k response has a 2xx status code
func (o *DcimInventoryItemsPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim inventory items partial update o k response has a 3xx status code
func (o *DcimInventoryItemsPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim inventory items partial update o k response has a 4xx status code
func (o *DcimInventoryItemsPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim inventory items partial update o k response has a 5xx status code
func (o *DcimInventoryItemsPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim inventory items partial update o k response a status code equal to that given
func (o *DcimInventoryItemsPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim inventory items partial update o k response
func (o *DcimInventoryItemsPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimInventoryItemsPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/inventory-items/{id}/][%d] dcimInventoryItemsPartialUpdateOK %s", 200, payload)
}

func (o *DcimInventoryItemsPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/inventory-items/{id}/][%d] dcimInventoryItemsPartialUpdateOK %s", 200, payload)
}

func (o *DcimInventoryItemsPartialUpdateOK) GetPayload() *models.InventoryItem {
	return o.Payload
}

func (o *DcimInventoryItemsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
