// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimRacksBulkUpdateReader is a Reader for the DcimRacksBulkUpdate structure.
type DcimRacksBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRacksBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimRacksBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/racks/] dcim_racks_bulk_update", response, response.Code())
	}
}

// NewDcimRacksBulkUpdateOK creates a DcimRacksBulkUpdateOK with default headers values
func NewDcimRacksBulkUpdateOK() *DcimRacksBulkUpdateOK {
	return &DcimRacksBulkUpdateOK{}
}

/*
DcimRacksBulkUpdateOK describes a response with status code 200, with default header values.

DcimRacksBulkUpdateOK dcim racks bulk update o k
*/
type DcimRacksBulkUpdateOK struct {
	Payload *models.Rack
}

// IsSuccess returns true when this dcim racks bulk update o k response has a 2xx status code
func (o *DcimRacksBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim racks bulk update o k response has a 3xx status code
func (o *DcimRacksBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim racks bulk update o k response has a 4xx status code
func (o *DcimRacksBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim racks bulk update o k response has a 5xx status code
func (o *DcimRacksBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim racks bulk update o k response a status code equal to that given
func (o *DcimRacksBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim racks bulk update o k response
func (o *DcimRacksBulkUpdateOK) Code() int {
	return 200
}

func (o *DcimRacksBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/racks/][%d] dcimRacksBulkUpdateOK %s", 200, payload)
}

func (o *DcimRacksBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/racks/][%d] dcimRacksBulkUpdateOK %s", 200, payload)
}

func (o *DcimRacksBulkUpdateOK) GetPayload() *models.Rack {
	return o.Payload
}

func (o *DcimRacksBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
