// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimManufacturersDeleteReader is a Reader for the DcimManufacturersDelete structure.
type DcimManufacturersDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimManufacturersDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimManufacturersDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/manufacturers/{id}/] dcim_manufacturers_delete", response, response.Code())
	}
}

// NewDcimManufacturersDeleteNoContent creates a DcimManufacturersDeleteNoContent with default headers values
func NewDcimManufacturersDeleteNoContent() *DcimManufacturersDeleteNoContent {
	return &DcimManufacturersDeleteNoContent{}
}

/*
DcimManufacturersDeleteNoContent describes a response with status code 204, with default header values.

DcimManufacturersDeleteNoContent dcim manufacturers delete no content
*/
type DcimManufacturersDeleteNoContent struct {
}

// IsSuccess returns true when this dcim manufacturers delete no content response has a 2xx status code
func (o *DcimManufacturersDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim manufacturers delete no content response has a 3xx status code
func (o *DcimManufacturersDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim manufacturers delete no content response has a 4xx status code
func (o *DcimManufacturersDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim manufacturers delete no content response has a 5xx status code
func (o *DcimManufacturersDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim manufacturers delete no content response a status code equal to that given
func (o *DcimManufacturersDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim manufacturers delete no content response
func (o *DcimManufacturersDeleteNoContent) Code() int {
	return 204
}

func (o *DcimManufacturersDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/manufacturers/{id}/][%d] dcimManufacturersDeleteNoContent", 204)
}

func (o *DcimManufacturersDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/manufacturers/{id}/][%d] dcimManufacturersDeleteNoContent", 204)
}

func (o *DcimManufacturersDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
