// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimRackRolesBulkPartialUpdateReader is a Reader for the DcimRackRolesBulkPartialUpdate structure.
type DcimRackRolesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackRolesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimRackRolesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/rack-roles/] dcim_rack-roles_bulk_partial_update", response, response.Code())
	}
}

// NewDcimRackRolesBulkPartialUpdateOK creates a DcimRackRolesBulkPartialUpdateOK with default headers values
func NewDcimRackRolesBulkPartialUpdateOK() *DcimRackRolesBulkPartialUpdateOK {
	return &DcimRackRolesBulkPartialUpdateOK{}
}

/*
DcimRackRolesBulkPartialUpdateOK describes a response with status code 200, with default header values.

DcimRackRolesBulkPartialUpdateOK dcim rack roles bulk partial update o k
*/
type DcimRackRolesBulkPartialUpdateOK struct {
	Payload *models.RackRole
}

// IsSuccess returns true when this dcim rack roles bulk partial update o k response has a 2xx status code
func (o *DcimRackRolesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack roles bulk partial update o k response has a 3xx status code
func (o *DcimRackRolesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack roles bulk partial update o k response has a 4xx status code
func (o *DcimRackRolesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack roles bulk partial update o k response has a 5xx status code
func (o *DcimRackRolesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack roles bulk partial update o k response a status code equal to that given
func (o *DcimRackRolesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim rack roles bulk partial update o k response
func (o *DcimRackRolesBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimRackRolesBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/rack-roles/][%d] dcimRackRolesBulkPartialUpdateOK %s", 200, payload)
}

func (o *DcimRackRolesBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/rack-roles/][%d] dcimRackRolesBulkPartialUpdateOK %s", 200, payload)
}

func (o *DcimRackRolesBulkPartialUpdateOK) GetPayload() *models.RackRole {
	return o.Payload
}

func (o *DcimRackRolesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RackRole)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
