// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimRacksReadReader is a Reader for the DcimRacksRead structure.
type DcimRacksReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRacksReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimRacksReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /dcim/racks/{id}/] dcim_racks_read", response, response.Code())
	}
}

// NewDcimRacksReadOK creates a DcimRacksReadOK with default headers values
func NewDcimRacksReadOK() *DcimRacksReadOK {
	return &DcimRacksReadOK{}
}

/*
DcimRacksReadOK describes a response with status code 200, with default header values.

DcimRacksReadOK dcim racks read o k
*/
type DcimRacksReadOK struct {
	Payload *models.Rack
}

// IsSuccess returns true when this dcim racks read o k response has a 2xx status code
func (o *DcimRacksReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim racks read o k response has a 3xx status code
func (o *DcimRacksReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim racks read o k response has a 4xx status code
func (o *DcimRacksReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim racks read o k response has a 5xx status code
func (o *DcimRacksReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim racks read o k response a status code equal to that given
func (o *DcimRacksReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim racks read o k response
func (o *DcimRacksReadOK) Code() int {
	return 200
}

func (o *DcimRacksReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/racks/{id}/][%d] dcimRacksReadOK %s", 200, payload)
}

func (o *DcimRacksReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/racks/{id}/][%d] dcimRacksReadOK %s", 200, payload)
}

func (o *DcimRacksReadOK) GetPayload() *models.Rack {
	return o.Payload
}

func (o *DcimRacksReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
