// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimPlatformsPartialUpdateReader is a Reader for the DcimPlatformsPartialUpdate structure.
type DcimPlatformsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimPlatformsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimPlatformsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/platforms/{id}/] dcim_platforms_partial_update", response, response.Code())
	}
}

// NewDcimPlatformsPartialUpdateOK creates a DcimPlatformsPartialUpdateOK with default headers values
func NewDcimPlatformsPartialUpdateOK() *DcimPlatformsPartialUpdateOK {
	return &DcimPlatformsPartialUpdateOK{}
}

/*
DcimPlatformsPartialUpdateOK describes a response with status code 200, with default header values.

DcimPlatformsPartialUpdateOK dcim platforms partial update o k
*/
type DcimPlatformsPartialUpdateOK struct {
	Payload *models.Platform
}

// IsSuccess returns true when this dcim platforms partial update o k response has a 2xx status code
func (o *DcimPlatformsPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim platforms partial update o k response has a 3xx status code
func (o *DcimPlatformsPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim platforms partial update o k response has a 4xx status code
func (o *DcimPlatformsPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim platforms partial update o k response has a 5xx status code
func (o *DcimPlatformsPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim platforms partial update o k response a status code equal to that given
func (o *DcimPlatformsPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim platforms partial update o k response
func (o *DcimPlatformsPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimPlatformsPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/platforms/{id}/][%d] dcimPlatformsPartialUpdateOK %s", 200, payload)
}

func (o *DcimPlatformsPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/platforms/{id}/][%d] dcimPlatformsPartialUpdateOK %s", 200, payload)
}

func (o *DcimPlatformsPartialUpdateOK) GetPayload() *models.Platform {
	return o.Payload
}

func (o *DcimPlatformsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Platform)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
