// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimRacksCreateReader is a Reader for the DcimRacksCreate structure.
type DcimRacksCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRacksCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimRacksCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /dcim/racks/] dcim_racks_create", response, response.Code())
	}
}

// NewDcimRacksCreateCreated creates a DcimRacksCreateCreated with default headers values
func NewDcimRacksCreateCreated() *DcimRacksCreateCreated {
	return &DcimRacksCreateCreated{}
}

/*
DcimRacksCreateCreated describes a response with status code 201, with default header values.

DcimRacksCreateCreated dcim racks create created
*/
type DcimRacksCreateCreated struct {
	Payload *models.Rack
}

// IsSuccess returns true when this dcim racks create created response has a 2xx status code
func (o *DcimRacksCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim racks create created response has a 3xx status code
func (o *DcimRacksCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim racks create created response has a 4xx status code
func (o *DcimRacksCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim racks create created response has a 5xx status code
func (o *DcimRacksCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim racks create created response a status code equal to that given
func (o *DcimRacksCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim racks create created response
func (o *DcimRacksCreateCreated) Code() int {
	return 201
}

func (o *DcimRacksCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/racks/][%d] dcimRacksCreateCreated %s", 201, payload)
}

func (o *DcimRacksCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/racks/][%d] dcimRacksCreateCreated %s", 201, payload)
}

func (o *DcimRacksCreateCreated) GetPayload() *models.Rack {
	return o.Payload
}

func (o *DcimRacksCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
