// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimConsolePortTemplatesDeleteReader is a Reader for the DcimConsolePortTemplatesDelete structure.
type DcimConsolePortTemplatesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimConsolePortTemplatesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimConsolePortTemplatesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/console-port-templates/{id}/] dcim_console-port-templates_delete", response, response.Code())
	}
}

// NewDcimConsolePortTemplatesDeleteNoContent creates a DcimConsolePortTemplatesDeleteNoContent with default headers values
func NewDcimConsolePortTemplatesDeleteNoContent() *DcimConsolePortTemplatesDeleteNoContent {
	return &DcimConsolePortTemplatesDeleteNoContent{}
}

/*
DcimConsolePortTemplatesDeleteNoContent describes a response with status code 204, with default header values.

DcimConsolePortTemplatesDeleteNoContent dcim console port templates delete no content
*/
type DcimConsolePortTemplatesDeleteNoContent struct {
}

// IsSuccess returns true when this dcim console port templates delete no content response has a 2xx status code
func (o *DcimConsolePortTemplatesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim console port templates delete no content response has a 3xx status code
func (o *DcimConsolePortTemplatesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim console port templates delete no content response has a 4xx status code
func (o *DcimConsolePortTemplatesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim console port templates delete no content response has a 5xx status code
func (o *DcimConsolePortTemplatesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim console port templates delete no content response a status code equal to that given
func (o *DcimConsolePortTemplatesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim console port templates delete no content response
func (o *DcimConsolePortTemplatesDeleteNoContent) Code() int {
	return 204
}

func (o *DcimConsolePortTemplatesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/console-port-templates/{id}/][%d] dcimConsolePortTemplatesDeleteNoContent", 204)
}

func (o *DcimConsolePortTemplatesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/console-port-templates/{id}/][%d] dcimConsolePortTemplatesDeleteNoContent", 204)
}

func (o *DcimConsolePortTemplatesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
