// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimFrontPortsUpdateReader is a Reader for the DcimFrontPortsUpdate structure.
type DcimFrontPortsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimFrontPortsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimFrontPortsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/front-ports/{id}/] dcim_front-ports_update", response, response.Code())
	}
}

// NewDcimFrontPortsUpdateOK creates a DcimFrontPortsUpdateOK with default headers values
func NewDcimFrontPortsUpdateOK() *DcimFrontPortsUpdateOK {
	return &DcimFrontPortsUpdateOK{}
}

/*
DcimFrontPortsUpdateOK describes a response with status code 200, with default header values.

DcimFrontPortsUpdateOK dcim front ports update o k
*/
type DcimFrontPortsUpdateOK struct {
	Payload *models.FrontPort
}

// IsSuccess returns true when this dcim front ports update o k response has a 2xx status code
func (o *DcimFrontPortsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim front ports update o k response has a 3xx status code
func (o *DcimFrontPortsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim front ports update o k response has a 4xx status code
func (o *DcimFrontPortsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim front ports update o k response has a 5xx status code
func (o *DcimFrontPortsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim front ports update o k response a status code equal to that given
func (o *DcimFrontPortsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim front ports update o k response
func (o *DcimFrontPortsUpdateOK) Code() int {
	return 200
}

func (o *DcimFrontPortsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/front-ports/{id}/][%d] dcimFrontPortsUpdateOK %s", 200, payload)
}

func (o *DcimFrontPortsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/front-ports/{id}/][%d] dcimFrontPortsUpdateOK %s", 200, payload)
}

func (o *DcimFrontPortsUpdateOK) GetPayload() *models.FrontPort {
	return o.Payload
}

func (o *DcimFrontPortsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FrontPort)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
