// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimSitesCreateReader is a Reader for the DcimSitesCreate structure.
type DcimSitesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimSitesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimSitesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /dcim/sites/] dcim_sites_create", response, response.Code())
	}
}

// NewDcimSitesCreateCreated creates a DcimSitesCreateCreated with default headers values
func NewDcimSitesCreateCreated() *DcimSitesCreateCreated {
	return &DcimSitesCreateCreated{}
}

/*
DcimSitesCreateCreated describes a response with status code 201, with default header values.

DcimSitesCreateCreated dcim sites create created
*/
type DcimSitesCreateCreated struct {
	Payload *models.Site
}

// IsSuccess returns true when this dcim sites create created response has a 2xx status code
func (o *DcimSitesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim sites create created response has a 3xx status code
func (o *DcimSitesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim sites create created response has a 4xx status code
func (o *DcimSitesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim sites create created response has a 5xx status code
func (o *DcimSitesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim sites create created response a status code equal to that given
func (o *DcimSitesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim sites create created response
func (o *DcimSitesCreateCreated) Code() int {
	return 201
}

func (o *DcimSitesCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/sites/][%d] dcimSitesCreateCreated %s", 201, payload)
}

func (o *DcimSitesCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/sites/][%d] dcimSitesCreateCreated %s", 201, payload)
}

func (o *DcimSitesCreateCreated) GetPayload() *models.Site {
	return o.Payload
}

func (o *DcimSitesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Site)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
