// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimInventoryItemTemplatesReadReader is a Reader for the DcimInventoryItemTemplatesRead structure.
type DcimInventoryItemTemplatesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInventoryItemTemplatesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInventoryItemTemplatesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /dcim/inventory-item-templates/{id}/] dcim_inventory-item-templates_read", response, response.Code())
	}
}

// NewDcimInventoryItemTemplatesReadOK creates a DcimInventoryItemTemplatesReadOK with default headers values
func NewDcimInventoryItemTemplatesReadOK() *DcimInventoryItemTemplatesReadOK {
	return &DcimInventoryItemTemplatesReadOK{}
}

/*
DcimInventoryItemTemplatesReadOK describes a response with status code 200, with default header values.

DcimInventoryItemTemplatesReadOK dcim inventory item templates read o k
*/
type DcimInventoryItemTemplatesReadOK struct {
	Payload *models.InventoryItemTemplate
}

// IsSuccess returns true when this dcim inventory item templates read o k response has a 2xx status code
func (o *DcimInventoryItemTemplatesReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim inventory item templates read o k response has a 3xx status code
func (o *DcimInventoryItemTemplatesReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim inventory item templates read o k response has a 4xx status code
func (o *DcimInventoryItemTemplatesReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim inventory item templates read o k response has a 5xx status code
func (o *DcimInventoryItemTemplatesReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim inventory item templates read o k response a status code equal to that given
func (o *DcimInventoryItemTemplatesReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim inventory item templates read o k response
func (o *DcimInventoryItemTemplatesReadOK) Code() int {
	return 200
}

func (o *DcimInventoryItemTemplatesReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/inventory-item-templates/{id}/][%d] dcimInventoryItemTemplatesReadOK %s", 200, payload)
}

func (o *DcimInventoryItemTemplatesReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dcim/inventory-item-templates/{id}/][%d] dcimInventoryItemTemplatesReadOK %s", 200, payload)
}

func (o *DcimInventoryItemTemplatesReadOK) GetPayload() *models.InventoryItemTemplate {
	return o.Payload
}

func (o *DcimInventoryItemTemplatesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InventoryItemTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
