// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimFrontPortTemplatesBulkPartialUpdateReader is a Reader for the DcimFrontPortTemplatesBulkPartialUpdate structure.
type DcimFrontPortTemplatesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimFrontPortTemplatesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimFrontPortTemplatesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/front-port-templates/] dcim_front-port-templates_bulk_partial_update", response, response.Code())
	}
}

// NewDcimFrontPortTemplatesBulkPartialUpdateOK creates a DcimFrontPortTemplatesBulkPartialUpdateOK with default headers values
func NewDcimFrontPortTemplatesBulkPartialUpdateOK() *DcimFrontPortTemplatesBulkPartialUpdateOK {
	return &DcimFrontPortTemplatesBulkPartialUpdateOK{}
}

/*
DcimFrontPortTemplatesBulkPartialUpdateOK describes a response with status code 200, with default header values.

DcimFrontPortTemplatesBulkPartialUpdateOK dcim front port templates bulk partial update o k
*/
type DcimFrontPortTemplatesBulkPartialUpdateOK struct {
	Payload *models.FrontPortTemplate
}

// IsSuccess returns true when this dcim front port templates bulk partial update o k response has a 2xx status code
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim front port templates bulk partial update o k response has a 3xx status code
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim front port templates bulk partial update o k response has a 4xx status code
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim front port templates bulk partial update o k response has a 5xx status code
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim front port templates bulk partial update o k response a status code equal to that given
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim front port templates bulk partial update o k response
func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/front-port-templates/][%d] dcimFrontPortTemplatesBulkPartialUpdateOK %s", 200, payload)
}

func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/front-port-templates/][%d] dcimFrontPortTemplatesBulkPartialUpdateOK %s", 200, payload)
}

func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) GetPayload() *models.FrontPortTemplate {
	return o.Payload
}

func (o *DcimFrontPortTemplatesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FrontPortTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
