// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// DcimDevicesCreateReader is a Reader for the DcimDevicesCreate structure.
type DcimDevicesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimDevicesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimDevicesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /dcim/devices/] dcim_devices_create", response, response.Code())
	}
}

// NewDcimDevicesCreateCreated creates a DcimDevicesCreateCreated with default headers values
func NewDcimDevicesCreateCreated() *DcimDevicesCreateCreated {
	return &DcimDevicesCreateCreated{}
}

/*
DcimDevicesCreateCreated describes a response with status code 201, with default header values.

DcimDevicesCreateCreated dcim devices create created
*/
type DcimDevicesCreateCreated struct {
	Payload *models.DeviceWithConfigContext
}

// IsSuccess returns true when this dcim devices create created response has a 2xx status code
func (o *DcimDevicesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim devices create created response has a 3xx status code
func (o *DcimDevicesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim devices create created response has a 4xx status code
func (o *DcimDevicesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim devices create created response has a 5xx status code
func (o *DcimDevicesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim devices create created response a status code equal to that given
func (o *DcimDevicesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim devices create created response
func (o *DcimDevicesCreateCreated) Code() int {
	return 201
}

func (o *DcimDevicesCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/][%d] dcimDevicesCreateCreated %s", 201, payload)
}

func (o *DcimDevicesCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/][%d] dcimDevicesCreateCreated %s", 201, payload)
}

func (o *DcimDevicesCreateCreated) GetPayload() *models.DeviceWithConfigContext {
	return o.Payload
}

func (o *DcimDevicesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceWithConfigContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
