// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersPermissionsDeleteReader is a Reader for the UsersPermissionsDelete structure.
type UsersPermissionsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersPermissionsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUsersPermissionsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /users/permissions/{id}/] users_permissions_delete", response, response.Code())
	}
}

// NewUsersPermissionsDeleteNoContent creates a UsersPermissionsDeleteNoContent with default headers values
func NewUsersPermissionsDeleteNoContent() *UsersPermissionsDeleteNoContent {
	return &UsersPermissionsDeleteNoContent{}
}

/*
UsersPermissionsDeleteNoContent describes a response with status code 204, with default header values.

UsersPermissionsDeleteNoContent users permissions delete no content
*/
type UsersPermissionsDeleteNoContent struct {
}

// IsSuccess returns true when this users permissions delete no content response has a 2xx status code
func (o *UsersPermissionsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users permissions delete no content response has a 3xx status code
func (o *UsersPermissionsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users permissions delete no content response has a 4xx status code
func (o *UsersPermissionsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this users permissions delete no content response has a 5xx status code
func (o *UsersPermissionsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this users permissions delete no content response a status code equal to that given
func (o *UsersPermissionsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the users permissions delete no content response
func (o *UsersPermissionsDeleteNoContent) Code() int {
	return 204
}

func (o *UsersPermissionsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/permissions/{id}/][%d] usersPermissionsDeleteNoContent", 204)
}

func (o *UsersPermissionsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /users/permissions/{id}/][%d] usersPermissionsDeleteNoContent", 204)
}

func (o *UsersPermissionsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
