// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// UsersPermissionsUpdateReader is a Reader for the UsersPermissionsUpdate structure.
type UsersPermissionsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersPermissionsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersPermissionsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /users/permissions/{id}/] users_permissions_update", response, response.Code())
	}
}

// NewUsersPermissionsUpdateOK creates a UsersPermissionsUpdateOK with default headers values
func NewUsersPermissionsUpdateOK() *UsersPermissionsUpdateOK {
	return &UsersPermissionsUpdateOK{}
}

/*
UsersPermissionsUpdateOK describes a response with status code 200, with default header values.

UsersPermissionsUpdateOK users permissions update o k
*/
type UsersPermissionsUpdateOK struct {
	Payload *models.ObjectPermission
}

// IsSuccess returns true when this users permissions update o k response has a 2xx status code
func (o *UsersPermissionsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users permissions update o k response has a 3xx status code
func (o *UsersPermissionsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users permissions update o k response has a 4xx status code
func (o *UsersPermissionsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users permissions update o k response has a 5xx status code
func (o *UsersPermissionsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users permissions update o k response a status code equal to that given
func (o *UsersPermissionsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users permissions update o k response
func (o *UsersPermissionsUpdateOK) Code() int {
	return 200
}

func (o *UsersPermissionsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/permissions/{id}/][%d] usersPermissionsUpdateOK %s", 200, payload)
}

func (o *UsersPermissionsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/permissions/{id}/][%d] usersPermissionsUpdateOK %s", 200, payload)
}

func (o *UsersPermissionsUpdateOK) GetPayload() *models.ObjectPermission {
	return o.Payload
}

func (o *UsersPermissionsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ObjectPermission)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
