// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimLocationsBulkDeleteReader is a Reader for the DcimLocationsBulkDelete structure.
type DcimLocationsBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimLocationsBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimLocationsBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/locations/] dcim_locations_bulk_delete", response, response.Code())
	}
}

// NewDcimLocationsBulkDeleteNoContent creates a DcimLocationsBulkDeleteNoContent with default headers values
func NewDcimLocationsBulkDeleteNoContent() *DcimLocationsBulkDeleteNoContent {
	return &DcimLocationsBulkDeleteNoContent{}
}

/*
DcimLocationsBulkDeleteNoContent describes a response with status code 204, with default header values.

DcimLocationsBulkDeleteNoContent dcim locations bulk delete no content
*/
type DcimLocationsBulkDeleteNoContent struct {
}

// IsSuccess returns true when this dcim locations bulk delete no content response has a 2xx status code
func (o *DcimLocationsBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim locations bulk delete no content response has a 3xx status code
func (o *DcimLocationsBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim locations bulk delete no content response has a 4xx status code
func (o *DcimLocationsBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim locations bulk delete no content response has a 5xx status code
func (o *DcimLocationsBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim locations bulk delete no content response a status code equal to that given
func (o *DcimLocationsBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim locations bulk delete no content response
func (o *DcimLocationsBulkDeleteNoContent) Code() int {
	return 204
}

func (o *DcimLocationsBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/locations/][%d] dcimLocationsBulkDeleteNoContent", 204)
}

func (o *DcimLocationsBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/locations/][%d] dcimLocationsBulkDeleteNoContent", 204)
}

func (o *DcimLocationsBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
