// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimDeviceBaysBulkUpdateReader is a Reader for the DcimDeviceBaysBulkUpdate structure.
type DcimDeviceBaysBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimDeviceBaysBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimDeviceBaysBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/device-bays/] dcim_device-bays_bulk_update", response, response.Code())
	}
}

// NewDcimDeviceBaysBulkUpdateOK creates a DcimDeviceBaysBulkUpdateOK with default headers values
func NewDcimDeviceBaysBulkUpdateOK() *DcimDeviceBaysBulkUpdateOK {
	return &DcimDeviceBaysBulkUpdateOK{}
}

/*
DcimDeviceBaysBulkUpdateOK describes a response with status code 200, with default header values.

DcimDeviceBaysBulkUpdateOK dcim device bays bulk update o k
*/
type DcimDeviceBaysBulkUpdateOK struct {
	Payload *models.DeviceBay
}

// IsSuccess returns true when this dcim device bays bulk update o k response has a 2xx status code
func (o *DcimDeviceBaysBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim device bays bulk update o k response has a 3xx status code
func (o *DcimDeviceBaysBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim device bays bulk update o k response has a 4xx status code
func (o *DcimDeviceBaysBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim device bays bulk update o k response has a 5xx status code
func (o *DcimDeviceBaysBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim device bays bulk update o k response a status code equal to that given
func (o *DcimDeviceBaysBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim device bays bulk update o k response
func (o *DcimDeviceBaysBulkUpdateOK) Code() int {
	return 200
}

func (o *DcimDeviceBaysBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/device-bays/][%d] dcimDeviceBaysBulkUpdateOK %s", 200, payload)
}

func (o *DcimDeviceBaysBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/device-bays/][%d] dcimDeviceBaysBulkUpdateOK %s", 200, payload)
}

func (o *DcimDeviceBaysBulkUpdateOK) GetPayload() *models.DeviceBay {
	return o.Payload
}

func (o *DcimDeviceBaysBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceBay)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
