// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimRackRolesDeleteReader is a Reader for the DcimRackRolesDelete structure.
type DcimRackRolesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackRolesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimRackRolesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/rack-roles/{id}/] dcim_rack-roles_delete", response, response.Code())
	}
}

// NewDcimRackRolesDeleteNoContent creates a DcimRackRolesDeleteNoContent with default headers values
func NewDcimRackRolesDeleteNoContent() *DcimRackRolesDeleteNoContent {
	return &DcimRackRolesDeleteNoContent{}
}

/*
DcimRackRolesDeleteNoContent describes a response with status code 204, with default header values.

DcimRackRolesDeleteNoContent dcim rack roles delete no content
*/
type DcimRackRolesDeleteNoContent struct {
}

// IsSuccess returns true when this dcim rack roles delete no content response has a 2xx status code
func (o *DcimRackRolesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack roles delete no content response has a 3xx status code
func (o *DcimRackRolesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack roles delete no content response has a 4xx status code
func (o *DcimRackRolesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack roles delete no content response has a 5xx status code
func (o *DcimRackRolesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack roles delete no content response a status code equal to that given
func (o *DcimRackRolesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim rack roles delete no content response
func (o *DcimRackRolesDeleteNoContent) Code() int {
	return 204
}

func (o *DcimRackRolesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/rack-roles/{id}/][%d] dcimRackRolesDeleteNoContent", 204)
}

func (o *DcimRackRolesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/rack-roles/{id}/][%d] dcimRackRolesDeleteNoContent", 204)
}

func (o *DcimRackRolesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
