// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimRackReservationsBulkDeleteReader is a Reader for the DcimRackReservationsBulkDelete structure.
type DcimRackReservationsBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackReservationsBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimRackReservationsBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /dcim/rack-reservations/] dcim_rack-reservations_bulk_delete", response, response.Code())
	}
}

// NewDcimRackReservationsBulkDeleteNoContent creates a DcimRackReservationsBulkDeleteNoContent with default headers values
func NewDcimRackReservationsBulkDeleteNoContent() *DcimRackReservationsBulkDeleteNoContent {
	return &DcimRackReservationsBulkDeleteNoContent{}
}

/*
DcimRackReservationsBulkDeleteNoContent describes a response with status code 204, with default header values.

DcimRackReservationsBulkDeleteNoContent dcim rack reservations bulk delete no content
*/
type DcimRackReservationsBulkDeleteNoContent struct {
}

// IsSuccess returns true when this dcim rack reservations bulk delete no content response has a 2xx status code
func (o *DcimRackReservationsBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack reservations bulk delete no content response has a 3xx status code
func (o *DcimRackReservationsBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack reservations bulk delete no content response has a 4xx status code
func (o *DcimRackReservationsBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack reservations bulk delete no content response has a 5xx status code
func (o *DcimRackReservationsBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack reservations bulk delete no content response a status code equal to that given
func (o *DcimRackReservationsBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim rack reservations bulk delete no content response
func (o *DcimRackReservationsBulkDeleteNoContent) Code() int {
	return 204
}

func (o *DcimRackReservationsBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/rack-reservations/][%d] dcimRackReservationsBulkDeleteNoContent", 204)
}

func (o *DcimRackReservationsBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/rack-reservations/][%d] dcimRackReservationsBulkDeleteNoContent", 204)
}

func (o *DcimRackReservationsBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
