// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimLocationsCreateReader is a Reader for the DcimLocationsCreate structure.
type DcimLocationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimLocationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimLocationsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /dcim/locations/] dcim_locations_create", response, response.Code())
	}
}

// NewDcimLocationsCreateCreated creates a DcimLocationsCreateCreated with default headers values
func NewDcimLocationsCreateCreated() *DcimLocationsCreateCreated {
	return &DcimLocationsCreateCreated{}
}

/*
DcimLocationsCreateCreated describes a response with status code 201, with default header values.

DcimLocationsCreateCreated dcim locations create created
*/
type DcimLocationsCreateCreated struct {
	Payload *models.Location
}

// IsSuccess returns true when this dcim locations create created response has a 2xx status code
func (o *DcimLocationsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim locations create created response has a 3xx status code
func (o *DcimLocationsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim locations create created response has a 4xx status code
func (o *DcimLocationsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim locations create created response has a 5xx status code
func (o *DcimLocationsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim locations create created response a status code equal to that given
func (o *DcimLocationsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim locations create created response
func (o *DcimLocationsCreateCreated) Code() int {
	return 201
}

func (o *DcimLocationsCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/locations/][%d] dcimLocationsCreateCreated %s", 201, payload)
}

func (o *DcimLocationsCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/locations/][%d] dcimLocationsCreateCreated %s", 201, payload)
}

func (o *DcimLocationsCreateCreated) GetPayload() *models.Location {
	return o.Payload
}

func (o *DcimLocationsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Location)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
