// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimInterfacesUpdateReader is a Reader for the DcimInterfacesUpdate structure.
type DcimInterfacesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimInterfacesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimInterfacesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/interfaces/{id}/] dcim_interfaces_update", response, response.Code())
	}
}

// NewDcimInterfacesUpdateOK creates a DcimInterfacesUpdateOK with default headers values
func NewDcimInterfacesUpdateOK() *DcimInterfacesUpdateOK {
	return &DcimInterfacesUpdateOK{}
}

/*
DcimInterfacesUpdateOK describes a response with status code 200, with default header values.

DcimInterfacesUpdateOK dcim interfaces update o k
*/
type DcimInterfacesUpdateOK struct {
	Payload *models.Interface
}

// IsSuccess returns true when this dcim interfaces update o k response has a 2xx status code
func (o *DcimInterfacesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim interfaces update o k response has a 3xx status code
func (o *DcimInterfacesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim interfaces update o k response has a 4xx status code
func (o *DcimInterfacesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim interfaces update o k response has a 5xx status code
func (o *DcimInterfacesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim interfaces update o k response a status code equal to that given
func (o *DcimInterfacesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim interfaces update o k response
func (o *DcimInterfacesUpdateOK) Code() int {
	return 200
}

func (o *DcimInterfacesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/interfaces/{id}/][%d] dcimInterfacesUpdateOK %s", 200, payload)
}

func (o *DcimInterfacesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/interfaces/{id}/][%d] dcimInterfacesUpdateOK %s", 200, payload)
}

func (o *DcimInterfacesUpdateOK) GetPayload() *models.Interface {
	return o.Payload
}

func (o *DcimInterfacesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Interface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
