// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimModulesPartialUpdateReader is a Reader for the DcimModulesPartialUpdate structure.
type DcimModulesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimModulesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimModulesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /dcim/modules/{id}/] dcim_modules_partial_update", response, response.Code())
	}
}

// NewDcimModulesPartialUpdateOK creates a DcimModulesPartialUpdateOK with default headers values
func NewDcimModulesPartialUpdateOK() *DcimModulesPartialUpdateOK {
	return &DcimModulesPartialUpdateOK{}
}

/*
DcimModulesPartialUpdateOK describes a response with status code 200, with default header values.

DcimModulesPartialUpdateOK dcim modules partial update o k
*/
type DcimModulesPartialUpdateOK struct {
	Payload *models.Module
}

// IsSuccess returns true when this dcim modules partial update o k response has a 2xx status code
func (o *DcimModulesPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim modules partial update o k response has a 3xx status code
func (o *DcimModulesPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim modules partial update o k response has a 4xx status code
func (o *DcimModulesPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim modules partial update o k response has a 5xx status code
func (o *DcimModulesPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim modules partial update o k response a status code equal to that given
func (o *DcimModulesPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim modules partial update o k response
func (o *DcimModulesPartialUpdateOK) Code() int {
	return 200
}

func (o *DcimModulesPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/modules/{id}/][%d] dcimModulesPartialUpdateOK %s", 200, payload)
}

func (o *DcimModulesPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /dcim/modules/{id}/][%d] dcimModulesPartialUpdateOK %s", 200, payload)
}

func (o *DcimModulesPartialUpdateOK) GetPayload() *models.Module {
	return o.Payload
}

func (o *DcimModulesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Module)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
