// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// DcimManufacturersUpdateReader is a Reader for the DcimManufacturersUpdate structure.
type DcimManufacturersUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimManufacturersUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimManufacturersUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /dcim/manufacturers/{id}/] dcim_manufacturers_update", response, response.Code())
	}
}

// NewDcimManufacturersUpdateOK creates a DcimManufacturersUpdateOK with default headers values
func NewDcimManufacturersUpdateOK() *DcimManufacturersUpdateOK {
	return &DcimManufacturersUpdateOK{}
}

/*
DcimManufacturersUpdateOK describes a response with status code 200, with default header values.

DcimManufacturersUpdateOK dcim manufacturers update o k
*/
type DcimManufacturersUpdateOK struct {
	Payload *models.Manufacturer
}

// IsSuccess returns true when this dcim manufacturers update o k response has a 2xx status code
func (o *DcimManufacturersUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim manufacturers update o k response has a 3xx status code
func (o *DcimManufacturersUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim manufacturers update o k response has a 4xx status code
func (o *DcimManufacturersUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim manufacturers update o k response has a 5xx status code
func (o *DcimManufacturersUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim manufacturers update o k response a status code equal to that given
func (o *DcimManufacturersUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim manufacturers update o k response
func (o *DcimManufacturersUpdateOK) Code() int {
	return 200
}

func (o *DcimManufacturersUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/manufacturers/{id}/][%d] dcimManufacturersUpdateOK %s", 200, payload)
}

func (o *DcimManufacturersUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /dcim/manufacturers/{id}/][%d] dcimManufacturersUpdateOK %s", 200, payload)
}

func (o *DcimManufacturersUpdateOK) GetPayload() *models.Manufacturer {
	return o.Payload
}

func (o *DcimManufacturersUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Manufacturer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
