// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// ExtrasCustomLinksReadReader is a Reader for the ExtrasCustomLinksRead structure.
type ExtrasCustomLinksReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomLinksReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasCustomLinksReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /extras/custom-links/{id}/] extras_custom-links_read", response, response.Code())
	}
}

// NewExtrasCustomLinksReadOK creates a ExtrasCustomLinksReadOK with default headers values
func NewExtrasCustomLinksReadOK() *ExtrasCustomLinksReadOK {
	return &ExtrasCustomLinksReadOK{}
}

/*
ExtrasCustomLinksReadOK describes a response with status code 200, with default header values.

ExtrasCustomLinksReadOK extras custom links read o k
*/
type ExtrasCustomLinksReadOK struct {
	Payload *models.CustomLink
}

// IsSuccess returns true when this extras custom links read o k response has a 2xx status code
func (o *ExtrasCustomLinksReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras custom links read o k response has a 3xx status code
func (o *ExtrasCustomLinksReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom links read o k response has a 4xx status code
func (o *ExtrasCustomLinksReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras custom links read o k response has a 5xx status code
func (o *ExtrasCustomLinksReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom links read o k response a status code equal to that given
func (o *ExtrasCustomLinksReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the extras custom links read o k response
func (o *ExtrasCustomLinksReadOK) Code() int {
	return 200
}

func (o *ExtrasCustomLinksReadOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/custom-links/{id}/][%d] extrasCustomLinksReadOK %s", 200, payload)
}

func (o *ExtrasCustomLinksReadOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /extras/custom-links/{id}/][%d] extrasCustomLinksReadOK %s", 200, payload)
}

func (o *ExtrasCustomLinksReadOK) GetPayload() *models.CustomLink {
	return o.Payload
}

func (o *ExtrasCustomLinksReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
