// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// NewExtrasConfigTemplatesBulkPartialUpdateParams creates a new ExtrasConfigTemplatesBulkPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExtrasConfigTemplatesBulkPartialUpdateParams() *ExtrasConfigTemplatesBulkPartialUpdateParams {
	return &ExtrasConfigTemplatesBulkPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExtrasConfigTemplatesBulkPartialUpdateParamsWithTimeout creates a new ExtrasConfigTemplatesBulkPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewExtrasConfigTemplatesBulkPartialUpdateParamsWithTimeout(timeout time.Duration) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	return &ExtrasConfigTemplatesBulkPartialUpdateParams{
		timeout: timeout,
	}
}

// NewExtrasConfigTemplatesBulkPartialUpdateParamsWithContext creates a new ExtrasConfigTemplatesBulkPartialUpdateParams object
// with the ability to set a context for a request.
func NewExtrasConfigTemplatesBulkPartialUpdateParamsWithContext(ctx context.Context) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	return &ExtrasConfigTemplatesBulkPartialUpdateParams{
		Context: ctx,
	}
}

// NewExtrasConfigTemplatesBulkPartialUpdateParamsWithHTTPClient creates a new ExtrasConfigTemplatesBulkPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewExtrasConfigTemplatesBulkPartialUpdateParamsWithHTTPClient(client *http.Client) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	return &ExtrasConfigTemplatesBulkPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
ExtrasConfigTemplatesBulkPartialUpdateParams contains all the parameters to send to the API endpoint

	for the extras config templates bulk partial update operation.

	Typically these are written to a http.Request.
*/
type ExtrasConfigTemplatesBulkPartialUpdateParams struct {

	// Data.
	Data *models.WritableConfigTemplate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the extras config templates bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WithDefaults() *ExtrasConfigTemplatesBulkPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the extras config templates bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WithTimeout(timeout time.Duration) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WithContext(ctx context.Context) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WithHTTPClient(client *http.Client) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WithData(data *models.WritableConfigTemplate) *ExtrasConfigTemplatesBulkPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the extras config templates bulk partial update params
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) SetData(data *models.WritableConfigTemplate) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *ExtrasConfigTemplatesBulkPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
