// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasWebhooksBulkDeleteReader is a Reader for the ExtrasWebhooksBulkDelete structure.
type ExtrasWebhooksBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasWebhooksBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExtrasWebhooksBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /extras/webhooks/] extras_webhooks_bulk_delete", response, response.Code())
	}
}

// NewExtrasWebhooksBulkDeleteNoContent creates a ExtrasWebhooksBulkDeleteNoContent with default headers values
func NewExtrasWebhooksBulkDeleteNoContent() *ExtrasWebhooksBulkDeleteNoContent {
	return &ExtrasWebhooksBulkDeleteNoContent{}
}

/*
ExtrasWebhooksBulkDeleteNoContent describes a response with status code 204, with default header values.

ExtrasWebhooksBulkDeleteNoContent extras webhooks bulk delete no content
*/
type ExtrasWebhooksBulkDeleteNoContent struct {
}

// IsSuccess returns true when this extras webhooks bulk delete no content response has a 2xx status code
func (o *ExtrasWebhooksBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras webhooks bulk delete no content response has a 3xx status code
func (o *ExtrasWebhooksBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras webhooks bulk delete no content response has a 4xx status code
func (o *ExtrasWebhooksBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras webhooks bulk delete no content response has a 5xx status code
func (o *ExtrasWebhooksBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this extras webhooks bulk delete no content response a status code equal to that given
func (o *ExtrasWebhooksBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the extras webhooks bulk delete no content response
func (o *ExtrasWebhooksBulkDeleteNoContent) Code() int {
	return 204
}

func (o *ExtrasWebhooksBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /extras/webhooks/][%d] extrasWebhooksBulkDeleteNoContent", 204)
}

func (o *ExtrasWebhooksBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /extras/webhooks/][%d] extrasWebhooksBulkDeleteNoContent", 204)
}

func (o *ExtrasWebhooksBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
