// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ExtrasCustomLinksBulkDeleteReader is a Reader for the ExtrasCustomLinksBulkDelete structure.
type ExtrasCustomLinksBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomLinksBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExtrasCustomLinksBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /extras/custom-links/] extras_custom-links_bulk_delete", response, response.Code())
	}
}

// NewExtrasCustomLinksBulkDeleteNoContent creates a ExtrasCustomLinksBulkDeleteNoContent with default headers values
func NewExtrasCustomLinksBulkDeleteNoContent() *ExtrasCustomLinksBulkDeleteNoContent {
	return &ExtrasCustomLinksBulkDeleteNoContent{}
}

/*
ExtrasCustomLinksBulkDeleteNoContent describes a response with status code 204, with default header values.

ExtrasCustomLinksBulkDeleteNoContent extras custom links bulk delete no content
*/
type ExtrasCustomLinksBulkDeleteNoContent struct {
}

// IsSuccess returns true when this extras custom links bulk delete no content response has a 2xx status code
func (o *ExtrasCustomLinksBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras custom links bulk delete no content response has a 3xx status code
func (o *ExtrasCustomLinksBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom links bulk delete no content response has a 4xx status code
func (o *ExtrasCustomLinksBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras custom links bulk delete no content response has a 5xx status code
func (o *ExtrasCustomLinksBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom links bulk delete no content response a status code equal to that given
func (o *ExtrasCustomLinksBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the extras custom links bulk delete no content response
func (o *ExtrasCustomLinksBulkDeleteNoContent) Code() int {
	return 204
}

func (o *ExtrasCustomLinksBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /extras/custom-links/][%d] extrasCustomLinksBulkDeleteNoContent", 204)
}

func (o *ExtrasCustomLinksBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /extras/custom-links/][%d] extrasCustomLinksBulkDeleteNoContent", 204)
}

func (o *ExtrasCustomLinksBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
