// Code generated by go-swagger; DO NOT EDIT.

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// ExtrasCustomFieldsBulkUpdateReader is a Reader for the ExtrasCustomFieldsBulkUpdate structure.
type ExtrasCustomFieldsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtrasCustomFieldsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtrasCustomFieldsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /extras/custom-fields/] extras_custom-fields_bulk_update", response, response.Code())
	}
}

// NewExtrasCustomFieldsBulkUpdateOK creates a ExtrasCustomFieldsBulkUpdateOK with default headers values
func NewExtrasCustomFieldsBulkUpdateOK() *ExtrasCustomFieldsBulkUpdateOK {
	return &ExtrasCustomFieldsBulkUpdateOK{}
}

/*
ExtrasCustomFieldsBulkUpdateOK describes a response with status code 200, with default header values.

ExtrasCustomFieldsBulkUpdateOK extras custom fields bulk update o k
*/
type ExtrasCustomFieldsBulkUpdateOK struct {
	Payload *models.CustomField
}

// IsSuccess returns true when this extras custom fields bulk update o k response has a 2xx status code
func (o *ExtrasCustomFieldsBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this extras custom fields bulk update o k response has a 3xx status code
func (o *ExtrasCustomFieldsBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this extras custom fields bulk update o k response has a 4xx status code
func (o *ExtrasCustomFieldsBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this extras custom fields bulk update o k response has a 5xx status code
func (o *ExtrasCustomFieldsBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this extras custom fields bulk update o k response a status code equal to that given
func (o *ExtrasCustomFieldsBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the extras custom fields bulk update o k response
func (o *ExtrasCustomFieldsBulkUpdateOK) Code() int {
	return 200
}

func (o *ExtrasCustomFieldsBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /extras/custom-fields/][%d] extrasCustomFieldsBulkUpdateOK %s", 200, payload)
}

func (o *ExtrasCustomFieldsBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /extras/custom-fields/][%d] extrasCustomFieldsBulkUpdateOK %s", 200, payload)
}

func (o *ExtrasCustomFieldsBulkUpdateOK) GetPayload() *models.CustomField {
	return o.Payload
}

func (o *ExtrasCustomFieldsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomField)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
