// Code generated by go-swagger; DO NOT EDIT.

package vpn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// VpnTunnelsDeleteReader is a Reader for the VpnTunnelsDelete structure.
type VpnTunnelsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VpnTunnelsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewVpnTunnelsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /vpn/tunnels/{id}/] vpn_tunnels_delete", response, response.Code())
	}
}

// NewVpnTunnelsDeleteNoContent creates a VpnTunnelsDeleteNoContent with default headers values
func NewVpnTunnelsDeleteNoContent() *VpnTunnelsDeleteNoContent {
	return &VpnTunnelsDeleteNoContent{}
}

/*
VpnTunnelsDeleteNoContent describes a response with status code 204, with default header values.

VpnTunnelsDeleteNoContent vpn tunnels delete no content
*/
type VpnTunnelsDeleteNoContent struct {
}

// IsSuccess returns true when this vpn tunnels delete no content response has a 2xx status code
func (o *VpnTunnelsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vpn tunnels delete no content response has a 3xx status code
func (o *VpnTunnelsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vpn tunnels delete no content response has a 4xx status code
func (o *VpnTunnelsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this vpn tunnels delete no content response has a 5xx status code
func (o *VpnTunnelsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this vpn tunnels delete no content response a status code equal to that given
func (o *VpnTunnelsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the vpn tunnels delete no content response
func (o *VpnTunnelsDeleteNoContent) Code() int {
	return 204
}

func (o *VpnTunnelsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /vpn/tunnels/{id}/][%d] vpnTunnelsDeleteNoContent", 204)
}

func (o *VpnTunnelsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /vpn/tunnels/{id}/][%d] vpnTunnelsDeleteNoContent", 204)
}

func (o *VpnTunnelsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
