// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// UsersTokensBulkPartialUpdateReader is a Reader for the UsersTokensBulkPartialUpdate structure.
type UsersTokensBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersTokensBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersTokensBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /users/tokens/] users_tokens_bulk_partial_update", response, response.Code())
	}
}

// NewUsersTokensBulkPartialUpdateOK creates a UsersTokensBulkPartialUpdateOK with default headers values
func NewUsersTokensBulkPartialUpdateOK() *UsersTokensBulkPartialUpdateOK {
	return &UsersTokensBulkPartialUpdateOK{}
}

/*
UsersTokensBulkPartialUpdateOK describes a response with status code 200, with default header values.

UsersTokensBulkPartialUpdateOK users tokens bulk partial update o k
*/
type UsersTokensBulkPartialUpdateOK struct {
	Payload *models.Token
}

// IsSuccess returns true when this users tokens bulk partial update o k response has a 2xx status code
func (o *UsersTokensBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users tokens bulk partial update o k response has a 3xx status code
func (o *UsersTokensBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users tokens bulk partial update o k response has a 4xx status code
func (o *UsersTokensBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users tokens bulk partial update o k response has a 5xx status code
func (o *UsersTokensBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users tokens bulk partial update o k response a status code equal to that given
func (o *UsersTokensBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users tokens bulk partial update o k response
func (o *UsersTokensBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *UsersTokensBulkPartialUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /users/tokens/][%d] usersTokensBulkPartialUpdateOK %s", 200, payload)
}

func (o *UsersTokensBulkPartialUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /users/tokens/][%d] usersTokensBulkPartialUpdateOK %s", 200, payload)
}

func (o *UsersTokensBulkPartialUpdateOK) GetPayload() *models.Token {
	return o.Payload
}

func (o *UsersTokensBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Token)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
