// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// UsersPermissionsBulkUpdateReader is a Reader for the UsersPermissionsBulkUpdate structure.
type UsersPermissionsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersPermissionsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUsersPermissionsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /users/permissions/] users_permissions_bulk_update", response, response.Code())
	}
}

// NewUsersPermissionsBulkUpdateOK creates a UsersPermissionsBulkUpdateOK with default headers values
func NewUsersPermissionsBulkUpdateOK() *UsersPermissionsBulkUpdateOK {
	return &UsersPermissionsBulkUpdateOK{}
}

/*
UsersPermissionsBulkUpdateOK describes a response with status code 200, with default header values.

UsersPermissionsBulkUpdateOK users permissions bulk update o k
*/
type UsersPermissionsBulkUpdateOK struct {
	Payload *models.ObjectPermission
}

// IsSuccess returns true when this users permissions bulk update o k response has a 2xx status code
func (o *UsersPermissionsBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this users permissions bulk update o k response has a 3xx status code
func (o *UsersPermissionsBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this users permissions bulk update o k response has a 4xx status code
func (o *UsersPermissionsBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this users permissions bulk update o k response has a 5xx status code
func (o *UsersPermissionsBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this users permissions bulk update o k response a status code equal to that given
func (o *UsersPermissionsBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the users permissions bulk update o k response
func (o *UsersPermissionsBulkUpdateOK) Code() int {
	return 200
}

func (o *UsersPermissionsBulkUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/permissions/][%d] usersPermissionsBulkUpdateOK %s", 200, payload)
}

func (o *UsersPermissionsBulkUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /users/permissions/][%d] usersPermissionsBulkUpdateOK %s", 200, payload)
}

func (o *UsersPermissionsBulkUpdateOK) GetPayload() *models.ObjectPermission {
	return o.Payload
}

func (o *UsersPermissionsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ObjectPermission)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
