// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WirelessWirelessLinksBulkDeleteReader is a Reader for the WirelessWirelessLinksBulkDelete structure.
type WirelessWirelessLinksBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WirelessWirelessLinksBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewWirelessWirelessLinksBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /wireless/wireless-links/] wireless_wireless-links_bulk_delete", response, response.Code())
	}
}

// NewWirelessWirelessLinksBulkDeleteNoContent creates a WirelessWirelessLinksBulkDeleteNoContent with default headers values
func NewWirelessWirelessLinksBulkDeleteNoContent() *WirelessWirelessLinksBulkDeleteNoContent {
	return &WirelessWirelessLinksBulkDeleteNoContent{}
}

/*
WirelessWirelessLinksBulkDeleteNoContent describes a response with status code 204, with default header values.

WirelessWirelessLinksBulkDeleteNoContent wireless wireless links bulk delete no content
*/
type WirelessWirelessLinksBulkDeleteNoContent struct {
}

// IsSuccess returns true when this wireless wireless links bulk delete no content response has a 2xx status code
func (o *WirelessWirelessLinksBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this wireless wireless links bulk delete no content response has a 3xx status code
func (o *WirelessWirelessLinksBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this wireless wireless links bulk delete no content response has a 4xx status code
func (o *WirelessWirelessLinksBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this wireless wireless links bulk delete no content response has a 5xx status code
func (o *WirelessWirelessLinksBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this wireless wireless links bulk delete no content response a status code equal to that given
func (o *WirelessWirelessLinksBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the wireless wireless links bulk delete no content response
func (o *WirelessWirelessLinksBulkDeleteNoContent) Code() int {
	return 204
}

func (o *WirelessWirelessLinksBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /wireless/wireless-links/][%d] wirelessWirelessLinksBulkDeleteNoContent", 204)
}

func (o *WirelessWirelessLinksBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /wireless/wireless-links/][%d] wirelessWirelessLinksBulkDeleteNoContent", 204)
}

func (o *WirelessWirelessLinksBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
