// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WirelessWirelessLanGroupsDeleteReader is a Reader for the WirelessWirelessLanGroupsDelete structure.
type WirelessWirelessLanGroupsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WirelessWirelessLanGroupsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewWirelessWirelessLanGroupsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /wireless/wireless-lan-groups/{id}/] wireless_wireless-lan-groups_delete", response, response.Code())
	}
}

// NewWirelessWirelessLanGroupsDeleteNoContent creates a WirelessWirelessLanGroupsDeleteNoContent with default headers values
func NewWirelessWirelessLanGroupsDeleteNoContent() *WirelessWirelessLanGroupsDeleteNoContent {
	return &WirelessWirelessLanGroupsDeleteNoContent{}
}

/*
WirelessWirelessLanGroupsDeleteNoContent describes a response with status code 204, with default header values.

WirelessWirelessLanGroupsDeleteNoContent wireless wireless lan groups delete no content
*/
type WirelessWirelessLanGroupsDeleteNoContent struct {
}

// IsSuccess returns true when this wireless wireless lan groups delete no content response has a 2xx status code
func (o *WirelessWirelessLanGroupsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this wireless wireless lan groups delete no content response has a 3xx status code
func (o *WirelessWirelessLanGroupsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this wireless wireless lan groups delete no content response has a 4xx status code
func (o *WirelessWirelessLanGroupsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this wireless wireless lan groups delete no content response has a 5xx status code
func (o *WirelessWirelessLanGroupsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this wireless wireless lan groups delete no content response a status code equal to that given
func (o *WirelessWirelessLanGroupsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the wireless wireless lan groups delete no content response
func (o *WirelessWirelessLanGroupsDeleteNoContent) Code() int {
	return 204
}

func (o *WirelessWirelessLanGroupsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsDeleteNoContent", 204)
}

func (o *WirelessWirelessLanGroupsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsDeleteNoContent", 204)
}

func (o *WirelessWirelessLanGroupsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
