// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/models"
)

// WirelessWirelessLanGroupsUpdateReader is a Reader for the WirelessWirelessLanGroupsUpdate structure.
type WirelessWirelessLanGroupsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WirelessWirelessLanGroupsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWirelessWirelessLanGroupsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /wireless/wireless-lan-groups/{id}/] wireless_wireless-lan-groups_update", response, response.Code())
	}
}

// NewWirelessWirelessLanGroupsUpdateOK creates a WirelessWirelessLanGroupsUpdateOK with default headers values
func NewWirelessWirelessLanGroupsUpdateOK() *WirelessWirelessLanGroupsUpdateOK {
	return &WirelessWirelessLanGroupsUpdateOK{}
}

/*
WirelessWirelessLanGroupsUpdateOK describes a response with status code 200, with default header values.

WirelessWirelessLanGroupsUpdateOK wireless wireless lan groups update o k
*/
type WirelessWirelessLanGroupsUpdateOK struct {
	Payload *models.WirelessLANGroup
}

// IsSuccess returns true when this wireless wireless lan groups update o k response has a 2xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this wireless wireless lan groups update o k response has a 3xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this wireless wireless lan groups update o k response has a 4xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this wireless wireless lan groups update o k response has a 5xx status code
func (o *WirelessWirelessLanGroupsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this wireless wireless lan groups update o k response a status code equal to that given
func (o *WirelessWirelessLanGroupsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the wireless wireless lan groups update o k response
func (o *WirelessWirelessLanGroupsUpdateOK) Code() int {
	return 200
}

func (o *WirelessWirelessLanGroupsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateOK %s", 200, payload)
}

func (o *WirelessWirelessLanGroupsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /wireless/wireless-lan-groups/{id}/][%d] wirelessWirelessLanGroupsUpdateOK %s", 200, payload)
}

func (o *WirelessWirelessLanGroupsUpdateOK) GetPayload() *models.WirelessLANGroup {
	return o.Payload
}

func (o *WirelessWirelessLanGroupsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WirelessLANGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
