// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scholdan/go-netbox/models"
)

// GetGatewayReader is a Reader for the GetGateway structure.
type GetGatewayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGatewayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGatewayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /plugins/nb-gateways/{id}] getGateway", response, response.Code())
	}
}

// NewGetGatewayOK creates a GetGatewayOK with default headers values
func NewGetGatewayOK() *GetGatewayOK {
	return &GetGatewayOK{}
}

/*
GetGatewayOK describes a response with status code 200, with default header values.

The requested gateway.
*/
type GetGatewayOK struct {
	Payload *models.Gateway
}

// IsSuccess returns true when this get gateway o k response has a 2xx status code
func (o *GetGatewayOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get gateway o k response has a 3xx status code
func (o *GetGatewayOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get gateway o k response has a 4xx status code
func (o *GetGatewayOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get gateway o k response has a 5xx status code
func (o *GetGatewayOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get gateway o k response a status code equal to that given
func (o *GetGatewayOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get gateway o k response
func (o *GetGatewayOK) Code() int {
	return 200
}

func (o *GetGatewayOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /plugins/nb-gateways/{id}][%d] getGatewayOK %s", 200, payload)
}

func (o *GetGatewayOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /plugins/nb-gateways/{id}][%d] getGatewayOK %s", 200, payload)
}

func (o *GetGatewayOK) GetPayload() *models.Gateway {
	return o.Payload
}

func (o *GetGatewayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Gateway)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
