// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteGatewayReader is a Reader for the DeleteGateway structure.
type DeleteGatewayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGatewayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteGatewayNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /gateways/{id}] deleteGateway", response, response.Code())
	}
}

// NewDeleteGatewayNoContent creates a DeleteGatewayNoContent with default headers values
func NewDeleteGatewayNoContent() *DeleteGatewayNoContent {
	return &DeleteGatewayNoContent{}
}

/*
DeleteGatewayNoContent describes a response with status code 204, with default header values.

Gateway deleted
*/
type DeleteGatewayNoContent struct {
}

// IsSuccess returns true when this delete gateway no content response has a 2xx status code
func (o *DeleteGatewayNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete gateway no content response has a 3xx status code
func (o *DeleteGatewayNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete gateway no content response has a 4xx status code
func (o *DeleteGatewayNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete gateway no content response has a 5xx status code
func (o *DeleteGatewayNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete gateway no content response a status code equal to that given
func (o *DeleteGatewayNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete gateway no content response
func (o *DeleteGatewayNoContent) Code() int {
	return 204
}

func (o *DeleteGatewayNoContent) Error() string {
	return fmt.Sprintf("[DELETE /gateways/{id}][%d] deleteGatewayNoContent", 204)
}

func (o *DeleteGatewayNoContent) String() string {
	return fmt.Sprintf("[DELETE /gateways/{id}][%d] deleteGatewayNoContent", 204)
}

func (o *DeleteGatewayNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
